// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Таблица за Код на вида воден обект по Наредба 7 - връзка между вид разрешително и водни обекти
    /// </summary>
    [Table("MapWaterTypePermitTypes", Schema = "RStRib")]
    [Index(nameof(PermitTypeId), Name = "IXFK_MapWaterTypePermitTypes_NCommercialFishingPermitTypes")]
    [Index(nameof(WaterTypeId), Name = "IXFK_MapWaterTypePermitTypes_NWaterTypes")]
    [Index(nameof(Code), nameof(ValidTo), Name = "UK_RStR_MapWaterTypePermitTypes", IsUnique = true)]
    public partial class MapWaterTypePermitType
    {
        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Код на вид воден обект
        /// </summary>
        [Required]
        [StringLength(50)]
        public string Code { get; set; }
        /// <summary>
        /// Име
        /// </summary>
        [Required]
        [StringLength(500)]
        public string Name { get; set; }
        /// <summary>
        /// Тип разрешително
        /// </summary>
        [Column("PermitTypeID")]
        public int? PermitTypeId { get; set; }
        /// <summary>
        /// Тип воден обект
        /// </summary>
        [Column("WaterTypeID")]
        public int? WaterTypeId { get; set; }
        /// <summary>
        /// Начална дата на валидност на записа
        /// </summary>
        public DateTime ValidFrom { get; set; }
        /// <summary>
        /// Крайна дата на валидност на записа
        /// </summary>
        public DateTime ValidTo { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(PermitTypeId))]
        [InverseProperty(nameof(NcommercialFishingPermitType.MapWaterTypePermitTypes))]
        public virtual NcommercialFishingPermitType PermitType { get; set; }
        [ForeignKey(nameof(WaterTypeId))]
        [InverseProperty(nameof(NwaterType.MapWaterTypePermitTypes))]
        public virtual NwaterType WaterType { get; set; }
    }
}