// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Типове прекратявания
    /// </summary>
    [Table("NSuspensionTypes", Schema = "RStRib")]
    [Index(nameof(Code), nameof(ValidTo), Name = "UK_RStR_NSuspensionTypes", IsUnique = true)]
    public partial class NsuspensionType
    {
        public NsuspensionType()
        {
            NsuspensionReasons = new HashSet<NsuspensionReason>();
        }

        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Код - Permanent, Temporary, TemporaryPermit
        /// </summary>
        [StringLength(50)]
        public string Code { get; set; }
        /// <summary>
        /// Име
        /// </summary>
        [Required]
        [StringLength(500)]
        public string Name { get; set; }
        /// <summary>
        /// Флаг дали типът на прекратяване се отнася за разрешително или за удостоверение.
        /// </summary>
        public bool IsPermit { get; set; }
        /// <summary>
        /// Флаг дали е безсрочно
        /// </summary>
        public bool IsUnlimited { get; set; }
        /// <summary>
        /// Начална дата на валидност на записа
        /// </summary>
        public DateTime ValidFrom { get; set; }
        /// <summary>
        /// Крайна дата на валидност на записа
        /// </summary>
        public DateTime ValidTo { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [InverseProperty(nameof(NsuspensionReason.SuspensionType))]
        public virtual ICollection<NsuspensionReason> NsuspensionReasons { get; set; }
    }
}