// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Басейни към съоръжение на аквакултурно стопанство
    /// </summary>
    [Table("AquacultureInstallationBasins", Schema = "RAquaSt")]
    [Index(nameof(AquacutureInstallationId), Name = "IXFK_AquacultureInstallBasins_AquacultureFacilityInstalls")]
    [Index(nameof(InstallationBasinId), Name = "IXFK_AquacultureInstallBasins_InstallationBasins")]
    [Index(nameof(AquacutureInstallationId), nameof(InstallationBasinId), Name = "UK_RAquaSt_AquacultureInstallationBasins", IsUnique = true)]
    public partial class AquacultureInstallationBasin
    {         public AquacultureInstallationBasin()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Съоръжение
        /// </summary>
        [Column("AquacutureInstallationID")]
        public int AquacutureInstallationId { get; set; }
        /// <summary>
        /// Басейн
        /// </summary>
        [Column("InstallationBasinID")]
        public int InstallationBasinId { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(AquacutureInstallationId))]
        [InverseProperty(nameof(AquacultureFacilityInstallation.AquacultureInstallationBasins))]
        public virtual AquacultureFacilityInstallation AquacutureInstallation { get; set; }
        [ForeignKey(nameof(InstallationBasinId))]
        [InverseProperty("AquacultureInstallationBasins")]
        public virtual InstallationBasin InstallationBasin { get; set; }
    }
}
