// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Удостоверения от БАБХ на аквакултурно стопанство
    /// </summary>
    [Table("AquacultureBabhCertificates", Schema = "RAquaSt")]
    [Index(nameof(AquacultureFacilityId), Name = "IXFK_AquacultureBabhCertificates_AquacultureFacilityRegister")]
    [Index(nameof(AquacultureFacilityId), nameof(CertificateValidTo), Name = "UK_RAquaSt_AquacultureBabhCertificates", IsUnique = true)]
    public partial class AquacultureBabhCertificate
    {         public AquacultureBabhCertificate()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Уникален идентификатор на аквакултурно стопанство
        /// </summary>
        [Column("AquacultureFacilityID")]
        public int AquacultureFacilityId { get; set; }
        /// <summary>
        /// Номер на удостоверението
        /// </summary>
        [Required]
        [StringLength(50)]
        public string CertificateNum { get; set; }
        /// <summary>
        /// Издател на удостоверението
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CertificateIssuer { get; set; }
        /// <summary>
        /// Дата на издаване на удостоверението
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime CertificateIssueDate { get; set; }
        /// <summary>
        /// Начална дата на валидност на удостоверението
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime CertificateValidFrom { get; set; }
        /// <summary>
        /// Крайна дата на валидност на удостоверението
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime? CertificateValidTo { get; set; }
        /// <summary>
        /// Коментар
        /// </summary>
        [StringLength(4000)]
        public string Comments { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(AquacultureFacilityId))]
        [InverseProperty(nameof(AquacultureFacilityRegister.AquacultureBabhCertificates))]
        public virtual AquacultureFacilityRegister AquacultureFacility { get; set; }
    }
}
