// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    [Table("MDR_FA_BR_Def", Schema = "FLUX_FA")]
    public partial class MdrFaBrDef
    {
        [Key]
        [Column("ID")]
        public override int Id { get; set; }
        [Required]
        [StringLength(50)]
        public override string Code { get; set; }
        [Required]
        [StringLength(500)]
        public string EnDescription { get; set; }
        public DateTime ValidFrom { get; set; }
        public DateTime ValidTo { get; set; }
        [StringLength(500)]
        public string CreatedBy { get; set; }
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        [Column("BRLevel")]
        [StringLength(200)]
        public string Brlevel { get; set; }
        [Column("BRSubLevel")]
        [StringLength(50)]
        public string BrsubLevel { get; set; }
        [StringLength(300)]
        public string Field { get; set; }
        [Column("ENMessage")]
        [StringLength(200)]
        public string Enmessage { get; set; }
    }
}