// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Конфискувана риба към АУАН, НП или Инспекция
    /// </summary>
    [Table("ConfiscatedFish", Schema = "RInsp")]
    [Index("AuanregisterId", Name = "IXFK_ConfiscatedFish_AUANRegister")]
    [Index("InspectionId", Name = "IXFK_ConfiscatedFish_InspectionRegister")]
    [Index("ApplianceId", Name = "IXFK_ConfiscatedFish_NConfiscatedAppliances")]
    [Index("ConfiscationActionId", Name = "IXFK_ConfiscatedFish_NConfiscationActions")]
    [Index("FishId", Name = "IXFK_ConfiscatedFish_NFishes")]
    [Index("LawSectionId", Name = "IXFK_ConfiscatedFish_NLawSections")]
    [Index("TurbotSizeGroupId", Name = "IXFK_ConfiscatedFish_NTurbotSizeGroups")]
    [Index("PenalDecreeRegisterId", Name = "IXFK_ConfiscatedFish_PenalDecreesRegister")]
    public partial class ConfiscatedFish
    {         public ConfiscatedFish()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// АУАН
        /// </summary>
        [Column("AUANRegisterID")]
        public int? AuanregisterId { get; set; }
        /// <summary>
        /// Наказателно постановление
        /// </summary>
        [Column("PenalDecreeRegisterID")]
        public int? PenalDecreeRegisterId { get; set; }
        /// <summary>
        /// Вид риба
        /// </summary>
        [Column("FishID")]
        public int? FishId { get; set; }
        /// <summary>
        /// Конфискувано приспособление
        /// </summary>
        [Column("ApplianceID")]
        public int? ApplianceId { get; set; }
        /// <summary>
        /// Тегло (кг)
        /// </summary>
        [Precision(10, 2)]
        public decimal? Weight { get; set; }
        /// <summary>
        /// Брой
        /// </summary>
        public int? Count { get; set; }
        /// <summary>
        /// Размерна група за калкан
        /// </summary>
        [Column("TurbotSizeGroupID")]
        public int? TurbotSizeGroupId { get; set; }
        /// <summary>
        /// Предприето действие
        /// </summary>
        [Column("ConfiscationActionID")]
        public int ConfiscationActionId { get; set; }
        /// <summary>
        /// Бележки
        /// </summary>
        [StringLength(2000)]
        public string Comments { get; set; }
        /// <summary>
        /// ТЗ за съхранение
        /// </summary>
        [Column("TerritoryUnitID")]
        public int? TerritoryUnitId { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        [Column(TypeName = "timestamp without time zone")]
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        [Column(TypeName = "timestamp without time zone")]
        public DateTime? UpdatedOn { get; set; }
        /// <summary>
        /// Секция на закон
        /// </summary>
        [Column("LawSectionID")]
        public int? LawSectionId { get; set; }
        /// <summary>
        /// Дължина на приспособление
        /// </summary>
        public decimal? Length { get; set; }
        /// <summary>
        /// Инспекция
        /// </summary>
        [Column("InspectionID")]
        public int? InspectionId { get; set; }

        [ForeignKey("ApplianceId")]
        [InverseProperty("ConfiscatedFishes")]
        public virtual NconfiscatedAppliance Appliance { get; set; }
        [ForeignKey("AuanregisterId")]
        [InverseProperty("ConfiscatedFishes")]
        public virtual Auanregister Auanregister { get; set; }
        [ForeignKey("ConfiscationActionId")]
        [InverseProperty("ConfiscatedFishes")]
        public virtual NconfiscationAction ConfiscationAction { get; set; }
        [ForeignKey("FishId")]
        [InverseProperty("ConfiscatedFishes")]
        public virtual Nfish Fish { get; set; }
        [ForeignKey("InspectionId")]
        [InverseProperty("ConfiscatedFishes")]
        public virtual InspectionRegister Inspection { get; set; }
        [ForeignKey("LawSectionId")]
        [InverseProperty("ConfiscatedFishes")]
        public virtual NlawSection LawSection { get; set; }
        [ForeignKey("PenalDecreeRegisterId")]
        [InverseProperty("ConfiscatedFishes")]
        public virtual PenalDecreesRegister PenalDecreeRegister { get; set; }
        [ForeignKey("TurbotSizeGroupId")]
        [InverseProperty("ConfiscatedFishes")]
        public virtual NturbotSizeGroup TurbotSizeGroup { get; set; }
    }
}
