// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Констативни протоколи от старата система
    /// </summary>
    [Table("ConstativeProtocolInspections", Schema = "RInsp")]
    [Index(nameof(InspectionId), Name = "IXFK_ConstativeProtocolInspections_InspectionRegister")]
    public partial class ConstativeProtocolInspection
    {         public ConstativeProtocolInspection()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Инспекция
        /// </summary>
        [Key]
        [Column("InspectionID")]
        public int InspectionId { get; set; }
        /// <summary>
        /// Местоположение
        /// </summary>
        [StringLength(500)]
        public string Location { get; set; }
        /// <summary>
        /// Имена на инспектор
        /// </summary>
        [StringLength(500)]
        public string InspectorName { get; set; }
        /// <summary>
        /// Свидетел
        /// </summary>
        [StringLength(500)]
        public string Witness1Name { get; set; }
        [StringLength(500)]
        public string Witness2Name { get; set; }
        [StringLength(4000)]
        public string InspectedObjectName { get; set; }
        [StringLength(4000)]
        public string InspectedPersonName { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(InspectionId))]
        [InverseProperty(nameof(InspectionRegister.ConstativeProtocolInspection))]
        public virtual InspectionRegister Inspection { get; set; }
    }
}
