// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Проверки при инспектиране на кораб (тип Y/N/x/null)
    /// </summary>
    [Table("InspectionChecks", Schema = "RInsp")]
    [Index(nameof(CheckTypeId), Name = "IXFK_InspectionChecks_NInspectionCheckTypes")]
    [Index(nameof(InspectionId), nameof(CheckTypeId), nameof(InspectedShipType), nameof(UnregisteredObjectIdentifier), Name = "UK_RInsp_InspectionChecks", IsUnique = true)]
    public partial class InspectionCheck
    {         public InspectionCheck()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Вид на иснпектирания кораб (Inspected / TransboardSender / TransbroardReceiver )
        /// </summary>
        [Required]
        [StringLength(20)]
        public string InspectedShipType { get; set; }
        /// <summary>
        /// Инспекция
        /// </summary>
        [Column("InspectionID")]
        public int InspectionId { get; set; }
        /// <summary>
        /// Тип проверка
        /// </summary>
        [Column("CheckTypeID")]
        public int CheckTypeId { get; set; }
        /// <summary>
        /// Стойност на проверка според CheckType ( Y / N / X / null )
        /// </summary>
        [Required]
        [StringLength(1)]
        public string CheckValue { get; set; }
        /// <summary>
        /// Детайли, въведени от инспектор
        /// </summary>
        [StringLength(200)]
        public string Description { get; set; }
        /// <summary>
        /// Идентификатор на нов обект (дневник/УСР/декл. произход), който не съществува в регистъра и е добавен по време на проверката
        /// </summary>
        [StringLength(50)]
        public string UnregisteredObjectIdentifier { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(CheckTypeId))]
        [InverseProperty(nameof(NinspectionCheckType.InspectionChecks))]
        public virtual NinspectionCheckType CheckType { get; set; }
        [ForeignKey(nameof(InspectionId))]
        [InverseProperty(nameof(InspectionRegister.InspectionChecks))]
        public virtual InspectionRegister Inspection { get; set; }
    }
}
