// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Инспектори в системата
    /// </summary>
    [Table("Inspectors", Schema = "RInsp")]
    [Index(nameof(InstitutionId), Name = "IXFK_Inspectors_NInsititutions")]
    [Index(nameof(UnregisteredPersonId), Name = "IXFK_Inspectors_UnregisteredPersons")]
    [Index(nameof(UserId), Name = "IXFK_Inspectors_Users")]
    [Index(nameof(UserId), nameof(UnregisteredPersonId), Name = "UK_RInsp_Inspectors", IsUnique = true)]
    public partial class Inspector
    {
        public Inspector()
        {
            InspectionInspectors = new HashSet<InspectionInspector>();
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Идентификатор на потребител в системата (ако е регистриран в системата)
        /// </summary>
        [Column("UserID")]
        public int? UserId { get; set; }
        /// <summary>
        /// Идентификатор на инспектор в UnregisteredPersons, ако не съществува в системата
        /// </summary>
        [Column("UnregisteredPersonID")]
        public int? UnregisteredPersonId { get; set; }
        /// <summary>
        /// Институция от която е инспекторът NInsititutions 
        /// </summary>
        [Column("InstitutionID")]
        public int? InstitutionId { get; set; }
        /// <summary>
        /// Пореден номер на извършена инспекция (използва се за генериране на Inspections.ReportNum)
        /// </summary>
        public int InspectionSequenceNum { get; set; }
        /// <summary>
        /// Номер на служебна карта  (използва се за генериране на Inspections.ReportNum)
        /// </summary>
        [StringLength(5)]
        public string InspectorCardNum { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(InstitutionId))]
        [InverseProperty(nameof(Ninstitution.Inspectors))]
        public virtual Ninstitution Institution { get; set; }
        [ForeignKey(nameof(UnregisteredPersonId))]
        [InverseProperty("Inspectors")]
        public virtual UnregisteredPerson UnregisteredPerson { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("Inspectors")]
        public virtual User User { get; set; }
        [InverseProperty(nameof(InspectionInspector.Inspector))]
        public virtual ICollection<InspectionInspector> InspectionInspectors { get; set; }
    }
}