// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Инспектори за дадена инспекция
    /// </summary>
    [Table("InspectionInspectors", Schema = "RInsp")]
    [Index(nameof(InspectionId), Name = "IXFK_InspectionInspectors_InspectionsRegister")]
    [Index(nameof(InspectorId), Name = "IXFK_InspectionInspectors_Inspectors")]
    [Index(nameof(InspectionId), nameof(InspectorId), Name = "UK_RInsp_InspectionInspectors", IsUnique = true)]
    public partial class InspectionInspector
    {         public InspectionInspector()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Инспекция
        /// </summary>
        [Column("InspectionID")]
        public int InspectionId { get; set; }
        /// <summary>
        /// Инспектор
        /// </summary>
        [Column("InspectorID")]
        public int InspectorId { get; set; }
        /// <summary>
        /// В качество на Отговорен инспектор или не
        /// </summary>
        public bool IsInCharge { get; set; }
        /// <summary>
        /// Инспекторът се е идентифицирал по време на инспекцията
        /// </summary>
        public bool? HasIdentifiedHimself { get; set; }
        /// <summary>
        /// Пореден номер за подредба
        /// </summary>
        public short? OrderNum { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(InspectionId))]
        [InverseProperty(nameof(InspectionRegister.InspectionInspectors))]
        public virtual InspectionRegister Inspection { get; set; }
        [ForeignKey(nameof(InspectorId))]
        [InverseProperty("InspectionInspectors")]
        public virtual Inspector Inspector { get; set; }
    }
}
