// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Размер на обезщетението към НП
    /// </summary>
    [Table("PenalDecreeFishCompensations", Schema = "RInsp")]
    [Index(nameof(FishId), Name = "IXFK_PenalDecreeFishCompensations_NFishes")]
    [Index(nameof(PenalDecreeRegisterId), Name = "IXFK_PenalDecreeFishCompensations_PenalDecreesRegister")]
    public partial class PenalDecreeFishCompensation
    {         public PenalDecreeFishCompensation()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Наказателно постановление
        /// </summary>
        [Column("PenalDecreeRegisterID")]
        public int PenalDecreeRegisterId { get; set; }
        /// <summary>
        /// Вид риба
        /// </summary>
        [Column("FishID")]
        public int FishId { get; set; }
        /// <summary>
        /// Тегло (кг)
        /// </summary>
        public decimal? Weight { get; set; }
        /// <summary>
        /// Брой
        /// </summary>
        public int? Count { get; set; }
        /// <summary>
        /// Предприето действие
        /// </summary>
        public decimal UnitPrice { get; set; }
        /// <summary>
        /// Бележки
        /// </summary>
        public decimal TotalPrice { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(FishId))]
        [InverseProperty(nameof(Nfish.PenalDecreeFishCompensations))]
        public virtual Nfish Fish { get; set; }
        [ForeignKey(nameof(PenalDecreeRegisterId))]
        [InverseProperty(nameof(PenalDecreesRegister.PenalDecreeFishCompensations))]
        public virtual PenalDecreesRegister PenalDecreeRegister { get; set; }
    }
}
