// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NetTopologySuite.Geometries;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Проверки на воден обект без извършване на инспекция
    /// </summary>
    [Table("WaterObjectChecks", Schema = "RInsp")]
    [Index(nameof(WaterObjectTypeId), Name = "IXFK_WaterObjectChecks_NWaterBodyTypes")]
    public partial class WaterObjectCheck
    {         public WaterObjectCheck()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Инспекция
        /// </summary>
        [Key]
        [Column("InspectionID")]
        public int InspectionId { get; set; }
        /// <summary>
        /// Вид водeн обект
        /// </summary>
        [Column("WaterObjectTypeID")]
        public int? WaterObjectTypeId { get; set; }
        /// <summary>
        /// Име на водния обект
        /// </summary>
        [StringLength(500)]
        public string Name { get; set; }
        /// <summary>
        /// Координати на воден обект
        /// </summary>
        [Column(TypeName = "geometry(Point)")]
        public Point WaterObjectCoordinates { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(InspectionId))]
        [InverseProperty(nameof(InspectionRegister.WaterObjectCheck))]
        public virtual InspectionRegister Inspection { get; set; }
        [ForeignKey(nameof(WaterObjectTypeId))]
        [InverseProperty(nameof(NwaterBodyType.WaterObjectChecks))]
        public virtual NwaterBodyType WaterObjectType { get; set; }
    }
}
