// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Кеш на направени проверки срещу RegiX
    /// </summary>
    [Table("ApplicationRegiXCache", Schema = "Appl")]
    [Index(nameof(WebServiceName), nameof(EgnLnc), nameof(Eik), nameof(ResponseDateTime), Name = "IX_Appl_ApplicationRegiXCache_WebSvc_EGN_EIK_ResponseDate")]
    public partial class ApplicationRegiXcache
    {         public ApplicationRegiXcache()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Име на извиканата услуга в RegiX (пр. TechnoLogica.RegiX.GraoNBDAdapter.APIService.INBDAPI.PersonDataSearch)
        /// </summary>
        [Required]
        [StringLength(500)]
        public string WebServiceName { get; set; }
        /// <summary>
        /// ЕГН / ЛНЧ
        /// </summary>
        [Column("EGN_LNC")]
        [StringLength(20)]
        public string EgnLnc { get; set; }
        /// <summary>
        /// ЕИК/БУЛСТАТ
        /// </summary>
        [Column("EIK")]
        [StringLength(50)]
        public string Eik { get; set; }
        /// <summary>
        /// Съдържание на заявката
        /// </summary>
        [Required]
        public string RequestContent { get; set; }
        /// <summary>
        /// Дата и час на подаване на заявката
        /// </summary>
        public DateTime ResponseDateTime { get; set; }
        /// <summary>
        /// Съдържание на отговора
        /// </summary>
        public string ResponseContent { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }
    }
}
