// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Потребители подписващи документи по заявления
    /// </summary>
    [Table("ApplicationPrintSignUsers", Schema = "Appl")]
    [Index("ApplicationTypeId", Name = "IXFK_ApplicationPrintSignUsers_NApplicationTypes")]
    [Index("TerritoryUnitId", Name = "IXFK_ApplicationPrintSignUsers_NTerritoryUnits")]
    [Index("SignUserId", Name = "IXFK_ApplicationPrintSignUsers_SignUsers")]
    [Index("SubstituteUserId", Name = "IXFK_ApplicationPrintSignUsers_SubstUsers")]
    [Index("ApplicationTypeId", "TerritoryUnitId", Name = "UK_ApplicationPrintSignUsers", IsUnique = true)]
    public partial class ApplicationPrintSignUser
    {         public ApplicationPrintSignUser()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Териториално звено (ако е празно - за всички)
        /// </summary>
        [Column("TerritoryUnitID")]
        public int? TerritoryUnitId { get; set; }
        /// <summary>
        /// Заявление (ако е празно - за всички)
        /// </summary>
        [Column("ApplicationTypeID")]
        public int? ApplicationTypeId { get; set; }
        /// <summary>
        /// Подписващ потребител
        /// </summary>
        [Column("SignUserID")]
        public int SignUserId { get; set; }
        /// <summary>
        /// Заместващ потребител
        /// </summary>
        [Column("SubstituteUserID")]
        public int? SubstituteUserId { get; set; }
        /// <summary>
        /// Заповед за заместване
        /// </summary>
        [StringLength(1000)]
        public string SubstituteReason { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        [Column(TypeName = "timestamp without time zone")]
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        [Column(TypeName = "timestamp without time zone")]
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey("ApplicationTypeId")]
        [InverseProperty("ApplicationPrintSignUsers")]
        public virtual NapplicationType ApplicationType { get; set; }
        [ForeignKey("SignUserId")]
        [InverseProperty("ApplicationPrintSignUserSignUsers")]
        public virtual User SignUser { get; set; }
        [ForeignKey("SubstituteUserId")]
        [InverseProperty("ApplicationPrintSignUserSubstituteUsers")]
        public virtual User SubstituteUser { get; set; }
        [ForeignKey("TerritoryUnitId")]
        [InverseProperty("ApplicationPrintSignUsers")]
        public virtual NterritoryUnit TerritoryUnit { get; set; }
    }
}
