// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Видове заявления за административни услуги за дадени видове процеси (йерархия на стъпките)
    /// </summary>
    [Table("NApplicationTypeHierTypes", Schema = "Appl")]
    [Index(nameof(ApplicationHierTypeId), Name = "IXFK_NApplicationTypeHierTypes_NApplicationStatusHierarchyTypes")]
    [Index(nameof(ApplicationTypeId), Name = "IXFK_NApplicationTypeHierTypes_NApplicationTypes")]
    [Index(nameof(ApplicationTypeId), nameof(ApplicationHierTypeId), Name = "UK_Appl_NApplicationTypeHierTypes", IsUnique = true)]
    public partial class NapplicationTypeHierType
    {         public NapplicationTypeHierType()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Тип заявление
        /// </summary>
        [Column("ApplicationTypeID")]
        public int ApplicationTypeId { get; set; }
        [Column("ApplicationHierTypeID")]
        public int ApplicationHierTypeId { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(ApplicationHierTypeId))]
        [InverseProperty(nameof(NapplicationStatusHierarchyType.NapplicationTypeHierTypes))]
        public virtual NapplicationStatusHierarchyType ApplicationHierType { get; set; }
        [ForeignKey(nameof(ApplicationTypeId))]
        [InverseProperty(nameof(NapplicationType.NapplicationTypeHierTypes))]
        public virtual NapplicationType ApplicationType { get; set; }
    }
}
