// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Права за достъп
    /// </summary>
    [Table("NPermissions", Schema = "UsrMgmt")]
    [Index(nameof(PermissionTypeId), Name = "IXFK_NPermissions_NPermissionTypes")]
    [Index(nameof(PermissionGroupId), Name = "IXFK_UsrMgmt_NPermissions_UsrMgmt_NPermissionGroups")]
    [Index(nameof(Name), nameof(ValidTo), Name = "UK_UsrMgmt_Permissions", IsUnique = true)]
    public partial class Npermission
    {
        public Npermission()
        {
            RolePermissions = new HashSet<RolePermission>();
        }

        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Тип на правото (Read/Add/Edit/Delete/Restore/Other)
        /// </summary>
        [Column("PermissionTypeID")]
        public int PermissionTypeId { get; set; }
        /// <summary>
        /// Име
        /// </summary>
        [Required]
        [StringLength(500)]
        public string Name { get; set; }
        /// <summary>
        /// Описание
        /// </summary>
        [StringLength(4000)]
        public string Description { get; set; }
        /// <summary>
        /// Начална дата на валидност на записа
        /// </summary>
        public DateTime ValidFrom { get; set; }
        /// <summary>
        /// Крайна дата на валидност на записа
        /// </summary>
        public DateTime ValidTo { get; set; }
        /// <summary>
        /// Група
        /// </summary>
        [Column("PermissionGroupID")]
        public int PermissionGroupId { get; set; }
        /// <summary>
        /// Пореден номер в интерфейса
        /// </summary>
        public short? OrderNo { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(PermissionGroupId))]
        [InverseProperty(nameof(NpermissionGroup.Npermissions))]
        public virtual NpermissionGroup PermissionGroup { get; set; }
        [ForeignKey(nameof(PermissionTypeId))]
        [InverseProperty(nameof(NpermissionType.Npermissions))]
        public virtual NpermissionType PermissionType { get; set; }
        [InverseProperty(nameof(RolePermission.Permission))]
        public virtual ICollection<RolePermission> RolePermissions { get; set; }
    }
}