// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Роли в системата
    /// </summary>
    [Table("Roles", Schema = "UsrMgmt")]
    [Index(nameof(Code), nameof(ValidTo), Name = "UK_UsrMgmt_Roles", IsUnique = true)]
    public partial class Role
    {
        public Role()
        {
            ReportRolePermissions = new HashSet<ReportRolePermission>();
            RolePermissions = new HashSet<RolePermission>();
            UserLegals = new HashSet<UserLegal>();
            UserRoles = new HashSet<UserRole>();
        }

        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Код
        /// </summary>
        [Required]
        [StringLength(50)]
        public string Code { get; set; }
        /// <summary>
        /// Име
        /// </summary>
        [Required]
        [StringLength(500)]
        public string Name { get; set; }
        /// <summary>
        /// Описание
        /// </summary>
        [StringLength(4000)]
        public string Description { get; set; }
        /// <summary>
        /// Флаг дали ролята е за публични потребители
        /// </summary>
        public bool HasPublicAccess { get; set; }
        /// <summary>
        /// Флаг дали ролята е за вътрешни потребители
        /// </summary>
        public bool HasInternalAccess { get; set; }
        /// <summary>
        /// A random value that must change whenever a user is persisted to the store
        /// </summary>
        [Required]
        [StringLength(100)]
        public string ConcurrencyStamp { get; set; }
        /// <summary>
        /// Начална дата на валидност на записа
        /// </summary>
        public DateTime ValidFrom { get; set; }
        /// <summary>
        /// Крайна дата на валидност на записа
        /// </summary>
        public DateTime ValidTo { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [InverseProperty(nameof(ReportRolePermission.Role))]
        public virtual ICollection<ReportRolePermission> ReportRolePermissions { get; set; }
        [InverseProperty(nameof(RolePermission.Role))]
        public virtual ICollection<RolePermission> RolePermissions { get; set; }
        [InverseProperty(nameof(UserLegal.Role))]
        public virtual ICollection<UserLegal> UserLegals { get; set; }
        [InverseProperty(nameof(UserRole.Role))]
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}