// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Мобилни устройства към потребител
    /// </summary>
    [Table("UserMobileDevices", Schema = "UsrMgmt")]
    [Index(nameof(UserId), Name = "IXFK_UserMobileDevices_Users")]
    [Index(nameof(Imei), nameof(UserId), Name = "UK_UsrMgmt_UserMobileDevices", IsUnique = true)]
    public partial class UserMobileDevice
    {         public UserMobileDevice()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Потребител
        /// </summary>
        [Column("UserID")]
        public int UserId { get; set; }
        /// <summary>
        /// IMEI номер
        /// </summary>
        [Required]
        [Column("IMEI")]
        [StringLength(50)]
        public string Imei { get; set; }
        /// <summary>
        /// Дата и час на заявка за достъп
        /// </summary>
        public DateTime RequestAccessDate { get; set; }
        /// <summary>
        /// Статус на устройството (Requested/Approved/Blocked)
        /// </summary>
        [Required]
        [StringLength(50)]
        public string AccessStatus { get; set; }
        /// <summary>
        /// Дата на последен успешен опит за вход
        /// </summary>
        public DateTime? LastLoginDate { get; set; }
        /// <summary>
        /// Вид устройство Phone/Tablet/..
        /// </summary>
        [StringLength(50)]
        public string DeviceType { get; set; }
        /// <summary>
        /// Операционна система и номер версия
        /// </summary>
        [Column("OSVersion")]
        [StringLength(100)]
        public string Osversion { get; set; }
        /// <summary>
        /// Модел на устройството
        /// </summary>
        [StringLength(500)]
        public string DeviceModel { get; set; }
        /// <summary>
        /// Номер на версията на приложението, която използват
        /// </summary>
        [StringLength(50)]
        public string AppVersion { get; set; }
        /// <summary>
        /// Firebase токен за изпращане на нотификации
        /// </summary>
        [StringLength(256)]
        public string FirebaseTokenKey { get; set; }
        /// <summary>
        /// GUID за ресетване на паролата
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("UserMobileDevices")]
        public virtual User User { get; set; }
    }
}
