// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Произведени, продадени и нереализирани количества за аквакултирни ИСФ
    /// </summary>
    [Table("AquacutlureFormStockingMaterials", Schema = "RInfStat")]
    [Index(nameof(AquacultureFormId), Name = "IXFK_AquaFormStMat_AquacutlureForms")]
    [Index(nameof(InstallationTypeId), Name = "IXFK_AquaFormStMat_NAquacultureInstallationTypes")]
    [Index(nameof(FishId), Name = "IXFK_AquacutlureFormStockingMaterials_NFishes")]
    [Index(nameof(AquacultureFormId), nameof(InstallationTypeId), nameof(ReportType), nameof(FishId), Name = "UK_RInfStat_AquacutlureFormStockingMaterials", IsUnique = true)]
    public partial class AquacutlureFormStockingMaterial
    {         public AquacutlureFormStockingMaterial()
        {
            this.IsActive = true;
        }


        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("AquacultureFormID")]
        public int AquacultureFormId { get; set; }
        /// <summary>
        /// За тип съоражение
        /// </summary>
        [Column("InstallationTypeID")]
        public int InstallationTypeId { get; set; }
        /// <summary>
        /// Вид отчет (Produced/Sold/Unrealized)
        /// </summary>
        [Required]
        [StringLength(20)]
        public string ReportType { get; set; }
        /// <summary>
        /// Вид риба
        /// </summary>
        [Column("FishID")]
        public int FishId { get; set; }
        public int? FishLarvaeCount { get; set; }
        /// <summary>
        /// Еднолентен материал (бр.)
        /// </summary>
        public int? OneStripBreedingMaterialCount { get; set; }
        /// <summary>
        /// Еднолентен материал (ср.т.гр)
        /// </summary>
        public decimal? OneStripBreedingMaterialWeight { get; set; }
        /// <summary>
        /// Едногодишен материал (бр)
        /// </summary>
        public int? OneYearBreedingMaterialCount { get; set; }
        /// <summary>
        /// Едногодишен материал (ср.т.гр.)
        /// </summary>
        public decimal? OneYearBreedingMaterialWeight { get; set; }
        /// <summary>
        /// За консумация (кг)
        /// </summary>
        public decimal? ForConsumptionWeight { get; set; }
        /// <summary>
        /// Хайвер за консумация (кг)
        /// </summary>
        public decimal? CaviarForConsumptionWeight { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(AquacultureFormId))]
        [InverseProperty(nameof(AquacutlureForm.AquacutlureFormStockingMaterials))]
        public virtual AquacutlureForm AquacultureForm { get; set; }
        [ForeignKey(nameof(FishId))]
        [InverseProperty(nameof(Nfish.AquacutlureFormStockingMaterials))]
        public virtual Nfish Fish { get; set; }
        [ForeignKey(nameof(InstallationTypeId))]
        [InverseProperty(nameof(NaquacultureInstallationType.AquacutlureFormStockingMaterials))]
        public virtual NaquacultureInstallationType InstallationType { get; set; }
    }
}
