// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Приложени препарати или лечение
    /// </summary>
    [Table("AquacutlureFormGivenMedicines", Schema = "RInfStat")]
    [Index(nameof(AquacultureFormId), Name = "IXFK_AquaMedicines_AquacutlureForms")]
    [Index(nameof(AquacultureFormId), nameof(Medicine), Name = "UK_RInfStat_AquacutlureFormGivenMedicines", IsUnique = true)]
    public partial class AquacutlureFormGivenMedicine
    {         public AquacutlureFormGivenMedicine()
        {
            this.IsActive = true;
        }


        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("AquacultureFormID")]
        public int AquacultureFormId { get; set; }
        /// <summary>
        /// Вид лекарство
        /// </summary>
        [Required]
        [StringLength(100)]
        public string Medicine { get; set; }
        /// <summary>
        /// Мъжки индивиди - брой
        /// </summary>
        public int? GivenGrams { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(AquacultureFormId))]
        [InverseProperty(nameof(AquacutlureForm.AquacutlureFormGivenMedicines))]
        public virtual AquacutlureForm AquacultureForm { get; set; }
    }
}
