// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Числова статистическа информация за ИСФ (Приходи от риболов, Разходи за екипаж, Стойност на труда, ...)
    /// </summary>
    [Table("EmployeeStatNumericValues", Schema = "RInfStat")]
    [Index(nameof(NumericStatTypeId), Name = "IXFK_EmployeeStatNumericValues_NNumericStatTypes")]
    [Index(nameof(StatisticalFormId), Name = "IXFK_EmployeeStatNumericValues_StatisticalFormsRegister")]
    [Index(nameof(StatisticalFormId), nameof(NumericStatTypeId), Name = "UK_RInfStat_EmployeeStatNumericValues", IsUnique = true)]
    public partial class EmployeeStatNumericValue
    {         public EmployeeStatNumericValue()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// ИСФ 
        /// </summary>
        [Column("StatisticalFormID")]
        public int StatisticalFormId { get; set; }
        /// <summary>
        /// Тип числова статистика
        /// </summary>
        [Column("NumericStatTypeID")]
        public int NumericStatTypeId { get; set; }
        /// <summary>
        /// Стойност на статистиката
        /// </summary>
        public decimal? StatValue { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Пореден номер
        /// </summary>
        public short? OrderNum { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(NumericStatTypeId))]
        [InverseProperty(nameof(NnumericStatType.EmployeeStatNumericValues))]
        public virtual NnumericStatType NumericStatType { get; set; }
        [ForeignKey(nameof(StatisticalFormId))]
        [InverseProperty(nameof(StatisticalFormsRegister.EmployeeStatNumericValues))]
        public virtual StatisticalFormsRegister StatisticalForm { get; set; }
    }
}
