// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Информация за заети лица
    /// </summary>
    [Table("EmployeeStatCounts", Schema = "RInfStat")]
    [Index(nameof(EmployeeStatTypeId), Name = "IXFK_EmployeeStatCounts_NEmployeeStatTypes")]
    [Index(nameof(StatisticalFormId), Name = "IXFK_EmployeeStatCounts_StatisticalFormsRegister")]
    [Index(nameof(StatisticalFormId), nameof(EmployeeStatTypeId), Name = "UK_RInfStat_EmployeeStatCounts", IsUnique = true)]
    public partial class EmployeeStatCount
    {         public EmployeeStatCount()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// ИСФ 
        /// </summary>
        [Column("StatisticalFormID")]
        public int StatisticalFormId { get; set; }
        /// <summary>
        /// Тип статистика
        /// </summary>
        [Column("EmployeeStatTypeID")]
        public int EmployeeStatTypeId { get; set; }
        /// <summary>
        /// Мъже със заплащане (бр.)
        /// </summary>
        public int? MenWithPayCount { get; set; }
        /// <summary>
        /// Мъже без заплащане (бр.)
        /// </summary>
        public int? MenWithouPayCount { get; set; }
        /// <summary>
        /// Жени със заплащане (бр.)
        /// </summary>
        public int? WomenWithPayCount { get; set; }
        /// <summary>
        /// Жени без заплащане (бр.)
        /// </summary>
        public int? WomenWithoutPayCount { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Пореден номер
        /// </summary>
        public short? OrderNum { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(EmployeeStatTypeId))]
        [InverseProperty(nameof(NemployeeStatType.EmployeeStatCounts))]
        public virtual NemployeeStatType EmployeeStatType { get; set; }
        [ForeignKey(nameof(StatisticalFormId))]
        [InverseProperty(nameof(StatisticalFormsRegister.EmployeeStatCounts))]
        public virtual StatisticalFormsRegister StatisticalForm { get; set; }
    }
}
