// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// ИСФ за преработка - тегла на преработени продукти
    /// </summary>
    [Table("ReworkProducts", Schema = "RInfStat")]
    [Index(nameof(ProductId), Name = "IXFK_ReworkProducts_NReworkProductTypes")]
    [Index(nameof(ReworkFormId), Name = "IXFK_ReworkProducts_ReworkForms")]
    [Index(nameof(ReworkFormId), nameof(ProductId), Name = "UK_RInfStat_ReworkProducts", IsUnique = true)]
    public partial class ReworkProduct
    {         public ReworkProduct()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// ИСФ за преработка
        /// </summary>
        [Column("ReworkFormID")]
        public int ReworkFormId { get; set; }
        /// <summary>
        /// Вид риба / суровина
        /// </summary>
        [Column("ProductID")]
        public int ProductId { get; set; }
        /// <summary>
        /// Количество в тонове
        /// </summary>
        public decimal QuantityTons { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(ProductId))]
        [InverseProperty(nameof(NreworkProductType.ReworkProducts))]
        public virtual NreworkProductType Product { get; set; }
        [ForeignKey(nameof(ReworkFormId))]
        [InverseProperty("ReworkProducts")]
        public virtual ReworkForm ReworkForm { get; set; }
    }
}
