// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// ИСФ за преработка - тегла на суровини
    /// </summary>
    [Table("ReworkRawMaterials", Schema = "RInfStat")]
    [Index(nameof(FishId), Name = "IXFK_ReworkRawMaterials_NFishes")]
    [Index(nameof(ReworkFormId), Name = "IXFK_ReworkRawMaterials_ReworkForms")]
    [Index(nameof(ReworkFormId), nameof(FishId), nameof(MaterialOrigin), Name = "UK_RInfStat_ReworkRawMaterials_MaterialOrigin", IsUnique = true)]
    public partial class ReworkRawMaterial
    {         public ReworkRawMaterial()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// ИСФ за преработка
        /// </summary>
        [Column("ReworkFormID")]
        public int ReworkFormId { get; set; }
        /// <summary>
        /// Вид риба / суровина
        /// </summary>
        [Column("FishID")]
        public int FishId { get; set; }
        /// <summary>
        /// Количество в тонове
        /// </summary>
        public decimal QuantityTons { get; set; }
        /// <summary>
        /// Произход (Catch=Улов/Aqua=Аквакултура)
        /// </summary>
        [Required]
        [StringLength(50)]
        public string MaterialOrigin { get; set; }
        /// <summary>
        /// Страна/Зона
        /// </summary>
        [StringLength(100)]
        public string CountryZone { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(FishId))]
        [InverseProperty(nameof(Nfish.ReworkRawMaterials))]
        public virtual Nfish Fish { get; set; }
        [ForeignKey(nameof(ReworkFormId))]
        [InverseProperty("ReworkRawMaterials")]
        public virtual ReworkForm ReworkForm { get; set; }
    }
}
