import { LogLevel, OpenIdConfiguration } from "angular-auth-oidc-client";

export const AuthConfiguration = {
    //hdParam?: string,
    //renewTimeBeforeTokenExpiresInSeconds: 36000,
    //secureRoutes?: string[],
    //storage?: any,
    authWellknownEndpoint: '/identity/.well-known/openid-configuration',
    autoCleanStateAfterAuthentication: true,
    autoUserinfo: true,
    clientId: '',
    disableIatOffsetValidation: false,
    disableRefreshIdTokenAuthTimeValidation: false,
    eagerLoadAuthWellKnownEndpoints: false,
    forbiddenRoute: "/unauthorized",
    historyCleanupOff: false,
    ignoreNonceAfterRefresh: false,
    issValidationOff: false,
    logLevel: LogLevel.Error,
    maxIdTokenIatOffsetAllowedInSeconds: 300,
    postLoginRoute: '/redirect',
    postLogoutRedirectUri: '/redirect',
    redirectUrl: '/redirect',
    renewUserInfoAfterTokenRenew: true,
    responseType: 'code',
    scope: 'openid profile',
    silentRenew: true,
    silentRenewUrl: '/assets/silent-renew.html',
    startCheckSession: false,
    stsServer: '',
    tokenRefreshInSeconds: 3600,
    triggerAuthorizationResultEvent: true,
    unauthorizedRoute: '/unauthorized',
    useRefreshToken: false,
    usePushedAuthorisationRequests: false
} as OpenIdConfiguration;