// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Видове материал на корпуса
    /// </summary>
    [Table("NHullMaterials", Schema = "RShips")]
    [Index(nameof(MdrVesselHullTypeId), Name = "IXFK_NHullMaterials_MDR_Vessel_Hull_Type")]
    [Index(nameof(ValidTo), nameof(Code), Name = "UK_RS_NHullMaterials", IsUnique = true)]
    public partial class NhullMaterial
    {
        public NhullMaterial()
        {
            ShipRegisters = new HashSet<ShipRegister>();
        }

        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Код
        /// </summary>
        [StringLength(3)]
        public string Code { get; set; }
        /// <summary>
        /// Име
        /// </summary>
        [Required]
        [StringLength(500)]
        public string Name { get; set; }
        /// <summary>
        /// FLUX ID
        /// </summary>
        [Column("MDR_Vessel_Hull_Type_ID")]
        public int? MdrVesselHullTypeId { get; set; }
        /// <summary>
        /// Начална дата на валидност на записа
        /// </summary>
        public DateTime ValidFrom { get; set; }
        /// <summary>
        /// Крайна дата на валидност на записа
        /// </summary>
        public DateTime ValidTo { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(MdrVesselHullTypeId))]
        [InverseProperty("NhullMaterials")]
        public virtual MdrVesselHullType MdrVesselHullType { get; set; }
        [InverseProperty(nameof(ShipRegister.HullMaterial))]
        public virtual ICollection<ShipRegister> ShipRegisters { get; set; }
    }
}