// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Собственици на кораби
    /// </summary>
    [Table("ShipOwners", Schema = "RShips")]
    [Index(nameof(OwnerLegalId), Name = "IXFK_RS_ShipOwners_ISS_Legals")]
    [Index(nameof(OwnerPersonId), Name = "IXFK_RS_ShipOwners_ISS_Persons")]
    [Index(nameof(ShipRegisterId), Name = "IXFK_ShipOwners_ShipRegister")]
    [Index(nameof(ShipRegisterId), nameof(OwnerPersonId), nameof(OwnerLegalId), Name = "UK_RS_ShipOwners", IsUnique = true)]
    public partial class ShipOwner
    {         public ShipOwner()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Кораб
        /// </summary>
        [Column("ShipRegisterID")]
        public int ShipRegisterId { get; set; }
        /// <summary>
        /// Флаг дали собственика е физическо лице (True=ФЛ / False=ЮЛ)
        /// </summary>
        public bool OwnerIsPerson { get; set; }
        /// <summary>
        /// Собственик физическо лице
        /// </summary>
        [Column("OwnerPersonID")]
        public int? OwnerPersonId { get; set; }
        /// <summary>
        /// Собственик юридическо лице
        /// </summary>
        [Column("OwnerLegalID")]
        public int? OwnerLegalId { get; set; }
        public short OwnedShare { get; set; }
        /// <summary>
        /// Флаг дали това лице е Титуляр на кораба
        /// </summary>
        public bool IsShipHolder { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(OwnerLegalId))]
        [InverseProperty(nameof(Legal.ShipOwners))]
        public virtual Legal OwnerLegal { get; set; }
        [ForeignKey(nameof(OwnerPersonId))]
        [InverseProperty(nameof(Person.ShipOwners))]
        public virtual Person OwnerPerson { get; set; }
        [ForeignKey(nameof(ShipRegisterId))]
        [InverseProperty("ShipOwners")]
        public virtual ShipRegister ShipRegister { get; set; }
    }
}
