// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.23471
//    <NameSpace>TechnoLogica.Authentication.EAuth.XSD</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.Authentication.EAuth.XSD
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.30855")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:bg:egov:eauth:1.0:saml:ext")]
    [System.Xml.Serialization.XmlRootAttribute("RequestedService", Namespace="urn:bg:egov:eauth:1.0:saml:ext", IsNullable=false)]
    public partial class RequestedServiceType {
        
        private string serviceField;
        
        private string providerField;
        
        /// <summary>
        /// The oid of the requested service
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("The oid of the requested service")]
        public string Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
        
        /// <summary>
        /// The administration which provides the electronic administrative
        /// service
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("The administration which provides the electronic administrative\n\t\t\t\t\tservice")]
        public string Provider {
            get {
                return this.providerField;
            }
            set {
                this.providerField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.30855")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:bg:egov:eauth:1.0:saml:ext")]
    [System.Xml.Serialization.XmlRootAttribute("SPContext", Namespace="urn:bg:egov:eauth:1.0:saml:ext", IsNullable=false)]
    public partial class SPContextType {
        
        private System.Xml.XmlElement[] anyField;
        
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.30855")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:bg:egov:eauth:1.0:saml:ext")]
    [System.Xml.Serialization.XmlRootAttribute("Claim", Namespace="urn:bg:egov:eauth:1.0:saml:ext", IsNullable=false)]
    public partial class ClaimType {
        
        private ClaimsTypeEnum uriField;
        
        private bool uriFieldSpecified;
        
        private bool requiredField;
        
        public ClaimType() {
            this.requiredField = true;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ClaimsTypeEnum uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uriSpecified {
            get {
                return this.uriFieldSpecified;
            }
            set {
                this.uriFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.30855")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:bg:egov:eauth:1.0:saml:ext")]
    public enum ClaimsTypeEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:egov:bg:eauth:1.0:attributes:eIdentifier")]
        urnegovbgeauth10attributeseIdentifier,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:egov:bg:eauth:1.0:attributes:givenName")]
        urnegovbgeauth10attributesgivenName,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:egov:bg:eauth:1.0:attributes:surname")]
        urnegovbgeauth10attributessurname,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:egov:bg:eauth:1.0:attributes:cannonicalName")]
        urnegovbgeauth10attributescannonicalName,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:egov:bg:eauth:1.0:attributes:gender")]
        urnegovbgeauth10attributesgender,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:egov:bg:eauth:1.0:attributes:dateOfBirth")]
        urnegovbgeauth10attributesdateOfBirth,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:egov:bg:eauth:1.0:attributes:nationalityCode")]
        urnegovbgeauth10attributesnationalityCode,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:egov:bg:eauth:1.0:attributes:canonicalResidenceAddress")]
        urnegovbgeauth10attributescanonicalResidenceAddress,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:egov:bg:eauth:1.0:attributes:eMail")]
        urnegovbgeauth10attributeseMail,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:egov:bg:eauth:1.0:attributes:adminOID")]
        urnegovbgeauth10attributesadminOID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:egov:bg:eauth:1.0:attributes:adminLegalIdentifier")]
        urnegovbgeauth10attributesadminLegalIdentifier,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:egov:bg:eauth:1.0:attributes:admLegalName")]
        urnegovbgeauth10attributesadmLegalName,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:egov:bg:eauth:1.0:attributes:admPosition")]
        urnegovbgeauth10attributesadmPosition,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:egov:bg:eauth:1.0:attributes:admUnit")]
        urnegovbgeauth10attributesadmUnit,
    }
}
