export enum NumericStatTypeGroupsEnum {
    IncomeAq,
    ExpenseAq,
    RawMatAq,
    DeathRate,
    IncomeRe,
    ExpenseRe,
    Subsides,
    Capital,
    FinRes,
    IncomeVe,
    ExpenseVe,
    WorkHours,
    FreeLabor,
    NumHours,
}