// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Данни за прекратяване/заличаване/отказ на регистровия запис
    /// </summary>
    [Table("CancellationDetails", Schema = "iss")]
    [Index(nameof(CancelReasonId), Name = "IXFK_CancellationDetails_NCancellationReasons")]
    public partial class CancellationDetail
    {
        public CancellationDetail()
        {
            ScientificPermitRegisters = new HashSet<ScientificPermitRegister>();
            ShipRegisters = new HashSet<ShipRegister>();
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Тип причина за прекратяване
        /// </summary>
        [Column("CancelReasonID")]
        public int CancelReasonId { get; set; }
        /// <summary>
        /// Дата на прекратяване
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime CancelDate { get; set; }
        /// <summary>
        /// Номер на заповед за прекратяване
        /// </summary>
        [StringLength(200)]
        public string IssueOrderNum { get; set; }
        /// <summary>
        /// Основание/Причина за отказа - свободен текст
        /// </summary>
        [StringLength(4000)]
        public string Description { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(CancelReasonId))]
        [InverseProperty(nameof(NcancellationReason.CancellationDetails))]
        public virtual NcancellationReason CancelReason { get; set; }
        [InverseProperty(nameof(ScientificPermitRegister.CancellationDetails))]
        public virtual ICollection<ScientificPermitRegister> ScientificPermitRegisters { get; set; }
        [InverseProperty(nameof(ShipRegister.CancellationDetails))]
        public virtual ICollection<ShipRegister> ShipRegisters { get; set; }
    }
}