// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Видове изисквани файлове за прикачване според вида документ
    /// </summary>
    [Table("NRequiredFileTypes", Schema = "iss")]
    [Index(nameof(FileTypeId), Name = "IXFK_NRequiredFileTypes_NFileTypes")]
    [Index(nameof(PageCode), Name = "IXFK_NRequiredFileTypes_NPageCodes")]
    [Index(nameof(PageCode), nameof(FileTypeId), nameof(ValidTo), Name = "UK_ISS_NRequiredFileTypes", IsUnique = true)]
    public partial class NrequiredFileType
    {
        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Код на форма за качване на файлове
        /// </summary>
        [Required]
        [StringLength(500)]
        public string PageCode { get; set; }
        /// <summary>
        /// Тип файл, който трябва да се качи
        /// </summary>
        [Column("FileTypeID")]
        public int FileTypeId { get; set; }
        /// <summary>
        /// Флаг дали този тип файл задъжително трябва да бъде качен към документа
        /// </summary>
        public bool IsMandatory { get; set; }
        /// <summary>
        /// Начална дата на валидност на записа
        /// </summary>
        public DateTime ValidFrom { get; set; }
        /// <summary>
        /// Крайна дата на валидност на записа
        /// </summary>
        public DateTime ValidTo { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(FileTypeId))]
        [InverseProperty(nameof(NfileType.NrequiredFileTypes))]
        public virtual NfileType FileType { get; set; }
        [ForeignKey(nameof(PageCode))]
        [InverseProperty(nameof(NpageCode.NrequiredFileTypes))]
        public virtual NpageCode PageCodeNavigation { get; set; }
    }
}