// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    [Table("MDR_Vessel_Port", Schema = "FLUX_Vessel")]
    public partial class MdrVesselPort
    {
        [Key]
        [Column("ID")]
        public override int Id { get; set; }
        [Required]
        [StringLength(50)]
        public override string Code { get; set; }
        [Required]
        [StringLength(500)]
        public string EnDescription { get; set; }
        public DateTime ValidFrom { get; set; }
        public DateTime ValidTo { get; set; }
        [StringLength(500)]
        public string CreatedBy { get; set; }
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        [StringLength(3)]
        public string Country { get; set; }
        [StringLength(1)]
        public string OuterInd { get; set; }
        [Column("NUTs")]
        [StringLength(5)]
        public string Nuts { get; set; }
    }
}