// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Минимални версии на страници в мобилното приложение, за да може да работи. Ако версията е по-малка от посочената, излиза предупреждение че трябва да качи версията до последна.
    /// </summary>
    [Table("NMobileVersions", Schema = "Admin")]
    [Index(nameof(PageCode), Name = "IXFK_NMobileVersions_NPageCodes")]
    [Index(nameof(PageCode), nameof(Ostype), Name = "UK_Admin_MobileVersions", IsUnique = true)]
    public partial class NmobileVersion
    {         public NmobileVersion()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Код на страница от приложението или MOBILE_PUBLIC_ALL или MOBILE_INSP_ALL
        /// </summary>
        [Required]
        [StringLength(500)]
        public string PageCode { get; set; }
        /// <summary>
        /// Минимален номер на версия за тази страница, която може да се поддържа
        /// </summary>
        public int ForceMinBuildNum { get; set; }
        /// <summary>
        /// Вид операционна система (Android, iOS, UWP)
        /// </summary>
        [Column("OSType")]
        [StringLength(20)]
        public string Ostype { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(PageCode))]
        [InverseProperty(nameof(NpageCode.NmobileVersions))]
        public virtual NpageCode PageCodeNavigation { get; set; }
    }
}
