// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Ресурси за преводи в приложението
    /// </summary>
    [Table("NTranslationResources", Schema = "Admin")]
    [Index(nameof(TranslationGroupId), Name = "IXFK_NTranslations_NTranslationGroups")]
    [Index(nameof(TranslationGroupId), nameof(Code), nameof(ValidTo), Name = "UK_Admin_NTranslationResources", IsUnique = true)]
    public partial class NtranslationResource
    {
        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Група за превод
        /// </summary>
        [Column("TranslationGroupID")]
        public int TranslationGroupId { get; set; }
        /// <summary>
        /// Код на ресурса
        /// </summary>
        [Required]
        [StringLength(100)]
        public string Code { get; set; }
        /// <summary>
        /// Стойност на превода на съответния език
        /// </summary>
        [StringLength(4000)]
        public string TranslationValue { get; set; }
        /// <summary>
        /// Вид ресурс (Label/Help)
        /// </summary>
        [Required]
        [StringLength(50)]
        public string ResourceType { get; set; }
        /// <summary>
        /// Начална дата на валидност на записа
        /// </summary>
        public DateTime ValidFrom { get; set; }
        /// <summary>
        /// Крайна дата на валидност на записа
        /// </summary>
        public DateTime ValidTo { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(TranslationGroupId))]
        [InverseProperty(nameof(NtranslationGroup.NtranslationResources))]
        public virtual NtranslationGroup TranslationGroup { get; set; }
    }
}