// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Групи ресурси за превод в приложението
    /// </summary>
    [Table("NTranslationGroups", Schema = "Admin")]
    [Index(nameof(Code), nameof(LanguageCode), nameof(ValidTo), nameof(TranslationType), Name = "UK_Admin_NTranslationGroups", IsUnique = true)]
    public partial class NtranslationGroup
    {
        public NtranslationGroup()
        {
            NtranslationResources = new HashSet<NtranslationResource>();
        }

        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Код на групата
        /// </summary>
        [Required]
        [StringLength(100)]
        public string Code { get; set; }
        /// <summary>
        /// Име
        /// </summary>
        [Required]
        [StringLength(500)]
        public string Name { get; set; }
        /// <summary>
        /// Код на език (BG/EN)
        /// </summary>
        [Required]
        [StringLength(2)]
        public string LanguageCode { get; set; }
        /// <summary>
        /// Вид превод (WEB/MOBILE_PUBLIC/MOBILE_INSP)
        /// </summary>
        [Required]
        [StringLength(20)]
        public string TranslationType { get; set; }
        /// <summary>
        /// Начална дата на валидност на записа
        /// </summary>
        public DateTime ValidFrom { get; set; }
        /// <summary>
        /// Крайна дата на валидност на записа
        /// </summary>
        public DateTime ValidTo { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [InverseProperty(nameof(NtranslationResource.TranslationGroup))]
        public virtual ICollection<NtranslationResource> NtranslationResources { get; set; }
    }
}