using IARA.DataAccess.Abstractions;
using IARA.EntityModels.Entities;
using Microsoft.EntityFrameworkCore;

namespace IARA.DataAccess
{
    public partial class IARADbContext : ILoggingDbContext, IUsersDbContext
    {
        public DbSet<AcquiredCapacityRegister> AcquiredCapacityRegister { get { return dbContext.AcquiredCapacityRegisters; } }
        public DbSet<AcquiredCapacityCertificate> AcquiredCapacityCertificates { get { return dbContext.AcquiredCapacityCertificates; } }
        public DbSet<Address> Addresses { get { return dbContext.Addresses; } }
        public DbSet<AdmissionLogBookPage> AdmissionLogBookPages { get { return dbContext.AdmissionLogBookPages; } }
        public DbSet<AdmissionLogBookPageFile> AdmissionLogBookPageFiles { get { return dbContext.AdmissionLogBookPageFiles; } }
        public DbSet<Application> Applications { get { return dbContext.Applications; } }
        public DbSet<ApplicationChangeHistory> ApplicationChangeHistories { get { return dbContext.ApplicationChangeHistories; } }
        public DbSet<ApplicationChangeHistoryFile> ApplicationChangeHistoryFiles { get { return dbContext.ApplicationChangeHistoryFiles; } }
        public DbSet<ApplicationChangeOfCircumstance> ApplicationChangeOfCircumstances { get { return dbContext.ApplicationChangeOfCircumstances; } }
        public DbSet<ApplicationDelivery> ApplicationDeliveries { get { return dbContext.ApplicationDeliveries; } }
        public DbSet<ApplicationFile> ApplicationFiles { get { return dbContext.ApplicationFiles; } }
        public DbSet<ApplicationPayment> ApplicationPayments { get { return dbContext.ApplicationPayments; } }
        public DbSet<ApplicationPaymentTariff> ApplicationPaymentTariffs { get { return dbContext.ApplicationPaymentTariffs; } }
        public DbSet<ApplicationRegiXcache> ApplicationRegiXcaches { get { return dbContext.ApplicationRegiXcaches; } }
        public DbSet<ApplicationRegiXcheck> ApplicationRegiXchecks { get { return dbContext.ApplicationRegiXchecks; } }
        public DbSet<AquacultureFacilityCoordinate> AquacultureFacilityCoordinates { get { return dbContext.AquacultureFacilityCoordinates; } }
        public DbSet<AquacultureFacilityFish> AquacultureFacilityFishes { get { return dbContext.AquacultureFacilityFishes; } }
        public DbSet<AquacultureFacilityInstallation> AquacultureFacilityInstallations { get { return dbContext.AquacultureFacilityInstallations; } }
        public DbSet<AquacultureFacilityRegister> AquacultureFacilitiesRegister { get { return dbContext.AquacultureFacilityRegisters; } }
        public DbSet<AquacultureFacilityStatus> AquacultureFacilityStatuses { get { return dbContext.AquacultureFacilityStatuses; } }
        public DbSet<AquacultureFacilityRegisterFile> AquacultureFacilityFiles { get { return dbContext.AquacultureFacilityRegisterFiles; } }
        public DbSet<AquacultureHatcheryEquipment> AquacultureHatcheryEquipment { get { return dbContext.AquacultureHatcheryEquipments; } }
        public DbSet<AquacultureInspection> AquacultureInspections { get { return dbContext.AquacultureInspections; } }
        public DbSet<AquacultureInstallationBasin> AquacultureInstallationBasins { get { return dbContext.AquacultureInstallationBasins; } }
        public DbSet<AquacultureInstallationCollector> AquacultureInstallationCollectors { get { return dbContext.AquacultureInstallationCollectors; } }
        public DbSet<AquacultureInstallationNetCage> AquacultureInstallationNetCages { get { return dbContext.AquacultureInstallationNetCages; } }
        public DbSet<AquacultureInstallationRaft> AquacultureInstallationRafts { get { return dbContext.AquacultureInstallationRafts; } }
        public DbSet<AquacultureInstallationRecirculatorySystem> AquacultureInstallationRecirculatorySystems { get { return dbContext.AquacultureInstallationRecirculatorySystems; } }
        public DbSet<AquacultureLogBookPage> AquacultureLogBookPages { get { return dbContext.AquacultureLogBookPages; } }
        public DbSet<AquacultureLogBookPageFile> AquacultureLogBookPageFiles { get { return dbContext.AquacultureLogBookPageFiles; } }
        public DbSet<AquacultureOvosCertificate> AquacultureOvosCertificates { get { return dbContext.AquacultureOvosCertificates; } }
        public DbSet<AquacultureBabhCertificate> AquacultureBabhCertificates { get { return dbContext.AquacultureBabhCertificates; } }
        public DbSet<AquacultureUsageDocument> AquacultureUsageDocuments { get { return dbContext.AquacultureUsageDocuments; } }
        public DbSet<AquacultureWaterLawCertificate> AquacultureWaterLawCertificates { get { return dbContext.AquacultureWaterLawCertificates; } }
        public DbSet<AquacutlureForm> AquacutlureForms { get { return dbContext.AquacutlureForms; } }
        public DbSet<AquacutlureFormBroodstock> AquacutlureFormBroodstocks { get { return dbContext.AquacutlureFormBroodstocks; } }
        public DbSet<AquacutlureFormGivenMedicine> AquacutlureFormGivenMedicines { get { return dbContext.AquacutlureFormGivenMedicines; } }
        public DbSet<AquacutlureFormStockingMaterial> AquacutlureFormStockingMaterials { get { return dbContext.AquacutlureFormStockingMaterials; } }
        public DbSet<AuanconfiscatedFish> AuanConfiscatedFishes { get { return dbContext.AuanconfiscatedFishes; } }
        public DbSet<AuanconfiscatedFishingGear> AuanConfiscatedFishingGear { get { return dbContext.AuanconfiscatedFishingGears; } }
        public DbSet<Auanregister> AuanRegister { get { return dbContext.Auanregisters; } }
        public DbSet<AuanregisterFile> AuanRegisterFiles { get { return dbContext.AuanregisterFiles; } }
        public DbSet<AuanviolatedRegulation> AuanViolatedRegulations { get { return dbContext.AuanviolatedRegulations; } }
        public DbSet<AuditLog> AuditLogs { get { return dbContext.AuditLogs; } }
        public DbSet<BuyerLicense> BuyerLicenses { get { return dbContext.BuyerLicenses; } }
        public DbSet<BuyerRegisterStatus> BuyerRegisterStatuses { get { return dbContext.BuyerRegisterStatuses; } }
        public DbSet<BuyerLicenseFile> BuyerLicenseFiles { get { return dbContext.BuyerLicenseFiles; } }
        public DbSet<BuyerPremiseUsageDocument> BuyerPremiseUsageDocuments { get { return dbContext.BuyerPremiseUsageDocuments; } }
        public DbSet<BuyerRegister> BuyerRegisters { get { return dbContext.BuyerRegisters; } }
        public DbSet<NbuyerStatus> NbuyerStatuses { get { return dbContext.NbuyerStatuses; } }
        public DbSet<BuyerRegisterFile> BuyersRegisterFiles { get { return dbContext.BuyerRegisterFiles; } }
        public DbSet<CancellationDetail> CancellationDetails { get { return dbContext.CancellationDetails; } }
        public DbSet<CapacityCertificatesRegister> CapacityCertificatesRegister { get { return dbContext.CapacityCertificatesRegisters; } }
        public DbSet<CapacityChangeHistory> CapacityChangeHistory { get { return dbContext.CapacityChangeHistories; } }
        public DbSet<CapacityChangeHistoryCertificate> CapacityChangeHistoryCertificates { get { return dbContext.CapacityChangeHistoryCertificates; } }
        public DbSet<CatchQuota> CatchQuotas { get { return dbContext.CatchQuotas; } }
        public DbSet<CatchQuotaFile> CatchQuotaFiles { get { return dbContext.CatchQuotaFiles; } }
        public DbSet<CatchQuotaUnloadPort> CatchQuotaUnloadPorts { get { return dbContext.CatchQuotaUnloadPorts; } }
        public DbSet<CatchQuotasHist> CatchQuotasHists { get { return dbContext.CatchQuotasHists; } }
        public DbSet<CatchRecord> CatchRecords { get { return dbContext.CatchRecords; } }
        public DbSet<CatchRecordFish> CatchRecordFish { get { return dbContext.CatchRecordFishes; } }
        public DbSet<ConstativeProtocolInspection> ConstativeProtocolInspections { get { return dbContext.ConstativeProtocolInspections; } }
        public DbSet<NcatchType> NcatchTypes { get { return dbContext.NcatchTypes; } }
        public DbSet<NfishSize> NfishSizes { get { return dbContext.NfishSizes; } }
        public DbSet<CountryCapacityRegister> CountryCapacityRegister { get { return dbContext.CountryCapacityRegisters; } }
        public DbSet<CrossCheck> CrossChecks { get { return dbContext.CrossChecks; } }
        public DbSet<CrossCheckResult> CrossCheckResults { get { return dbContext.CrossCheckResults; } }
        public DbSet<EmailAddress> EmailAddresses { get { return dbContext.EmailAddresses; } }
        public DbSet<EmployeeStatCount> EmployeeStatCounts { get { return dbContext.EmployeeStatCounts; } }
        public DbSet<EmployeeStatNumericValue> EmployeeStatNumericValues { get { return dbContext.EmployeeStatNumericValues; } }
        public DbSet<ErrorLog> ErrorLogs { get { return dbContext.ErrorLogs; } }
        public DbSet<File> Files { get { return dbContext.Files; } }
        public DbSet<FirstSaleInspection> FirstSaleInspections { get { return dbContext.FirstSaleInspections; } }
        public DbSet<FirstSaleLogBookPage> FirstSaleLogBookPages { get { return dbContext.FirstSaleLogBookPages; } }
        public DbSet<FirstSaleLogBookPageFile> FirstSaleLogBookPageFiles { get { return dbContext.FirstSaleLogBookPageFiles; } }
        public DbSet<FishVesselsForm> FishVesselsForms { get { return dbContext.FishVesselsForms; } }
        public DbSet<FishermanInspection> FishermanInspections { get { return dbContext.FishermanInspections; } }
        public DbSet<FishermenRegister> FishermenRegisters { get { return dbContext.FishermenRegisters; } }
        public DbSet<FishermenRegisterFile> FishermenRegisterFiles { get { return dbContext.FishermenRegisterFiles; } }
        public DbSet<FishingAssociation> FishingAssociations { get { return dbContext.FishingAssociations; } }
        public DbSet<FishingAssociationFile> FishingAssociationFiles { get { return dbContext.FishingAssociationFiles; } }
        public DbSet<FishingAssociationMember> FishingAssociationMembers { get { return dbContext.FishingAssociationMembers; } }
        public DbSet<FishingCatchRecord> FishingCatchRecords { get { return dbContext.FishingCatchRecords; } }
        public DbSet<FishingCatchRecordFile> CatchRecordFiles { get { return dbContext.FishingCatchRecordFiles; } }
        public DbSet<FishingCatchRecordFish> FishingCatchRecordFishes { get { return dbContext.FishingCatchRecordFishes; } }
        public DbSet<FishingGearCheck> FishingGearChecks { get { return dbContext.FishingGearChecks; } }
        public DbSet<FishingGearMark> FishingGearMarks { get { return dbContext.FishingGearMarks; } }
        public DbSet<FishingGearPinger> FishingGearPingers { get { return dbContext.FishingGearPingers; } }
        public DbSet<FishingGearRegister> FishingGearRegisters { get { return dbContext.FishingGearRegisters; } }
        public DbSet<FishingTicket> FishingTickets { get { return dbContext.FishingTickets; } }
        public DbSet<FishingTicketFile> FishingTicketFiles { get { return dbContext.FishingTicketFiles; } }
        public DbSet<Fluxflaprequest> Fluxflaprequests { get { return dbContext.Fluxflaprequests; } }
        public DbSet<Fluxfvmsrequest> Fluxfvmsrequests { get { return dbContext.Fluxfvmsrequests; } }
        public DbSet<HolderGroundsForUse> HolderGroundsForUses { get { return dbContext.HolderGroundsForUses; } }
        public DbSet<InspDelivery> InspDelivery { get { return dbContext.InspDeliveries; } }
        public DbSet<InspectedFishingGear> InspectedFishingGears { get { return dbContext.InspectedFishingGears; } }
        public DbSet<InspectedPerson> InspectedPersons { get { return dbContext.InspectedPersons; } }
        public DbSet<InspectionCatchMeasure> InspectionCatchMeasures { get { return dbContext.InspectionCatchMeasures; } }
        public DbSet<InspectionCheck> InspectionChecks { get { return dbContext.InspectionChecks; } }
        public DbSet<InspectionPermitLicense> InspectionPermitLicenses { get { return dbContext.InspectionPermitLicenses; } }
        public DbSet<InspectionLogBookPage> InspectionLogBookPages { get { return dbContext.InspectionLogBookPages; } }
        public DbSet<InspectionEngine> InspectionEngines { get { return dbContext.InspectionEngines; } }
        public DbSet<InspectionInspector> InspectionInspectors { get { return dbContext.InspectionInspectors; } }
        public DbSet<InspectionLastPortVisit> InspectionLastPortVisits { get { return dbContext.InspectionLastPortVisits; } }
        public DbSet<InspectionObservationText> InspectionObservationTexts { get { return dbContext.InspectionObservationTexts; } }
        public DbSet<InspectionObservationTool> InspectionObservationTools { get { return dbContext.InspectionObservationTools; } }
        public DbSet<InspectionPatrolVehicle> InspectionPatrolVehicles { get { return dbContext.InspectionPatrolVehicles; } }
        public DbSet<InspectionRegister> InspectionsRegister { get { return dbContext.InspectionRegisters; } }
        public DbSet<InspectionRegisterFile> InspectionRegisterFiles { get { return dbContext.InspectionRegisterFiles; } }
        public DbSet<InspectionVessel> InspectionVessels { get { return dbContext.InspectionVessels; } }
        public DbSet<InspectionVesselActivity> InspectionVesselActivities { get { return dbContext.InspectionVesselActivities; } }
        public DbSet<Inspector> Inspectors { get { return dbContext.Inspectors; } }
        public DbSet<InstallationAquarium> InstallationAquariums { get { return dbContext.InstallationAquariums; } }
        public DbSet<InstallationBasin> InstallationBasins { get { return dbContext.InstallationBasins; } }
        public DbSet<InstallationDam> InstallationDams { get { return dbContext.InstallationDams; } }
        public DbSet<Legal> Legals { get { return dbContext.Legals; } }
        public DbSet<LegalEmailAddress> LegalEmailAddresses { get { return dbContext.LegalEmailAddresses; } }
        public DbSet<LegalFile> LegalFiles { get { return dbContext.LegalFiles; } }
        public DbSet<LegalPhoneNumber> LegalPhoneNumbers { get { return dbContext.LegalPhoneNumbers; } }
        public DbSet<LegalsAddress> LegalsAddresses { get { return dbContext.LegalsAddresses; } }
        public DbSet<LetterOfAttorney> LetterOfAttorneys { get { return dbContext.LetterOfAttorneys; } }
        public DbSet<LogBook> LogBooks { get { return dbContext.LogBooks; } }
        public DbSet<LogBookPageProduct> LogBookPageProducts { get { return dbContext.LogBookPageProducts; } }
        public DbSet<LogBookPermitLicense> LogBookPermitLicenses { get { return dbContext.LogBookPermitLicenses; } }
        public DbSet<MapApplicationTypeDeliveryType> MapApplicationTypeDeliveryTypes { get { return dbContext.MapApplicationTypeDeliveryTypes; } }
        public DbSet<MapApplicationTypeSubmittedByRole> MapApplicationTypeSubmittedByRoles { get { return dbContext.MapApplicationTypeSubmittedByRoles; } }
        public DbSet<MapStatFormTypesEmployeeStatTypeGroup> MapStatFormTypesEmployeeStatTypeGroups { get { return dbContext.MapStatFormTypesEmployeeStatTypeGroups; } }
        public DbSet<MapStatFormTypesNumericStatTypeGroup> MapStatFormTypesNumericStatTypeGroups { get { return dbContext.MapStatFormTypesNumericStatTypeGroups; } }
        public DbSet<MapTariffFish> MapTariffFishes { get { return dbContext.MapTariffFishes; } }
        public DbSet<MapTariffFishingGear> MapTariffFishingGears { get { return dbContext.MapTariffFishingGears; } }
        public DbSet<MdrAcdrCatchStatus> MdrAcdrCatchStatuses { get { return dbContext.MdrAcdrCatchStatuses; } }
        public DbSet<MdrAgreementType> MdrAgreementTypes { get { return dbContext.MdrAgreementTypes; } }
        public DbSet<MdrBooleanType> MdrBooleanTypes { get { return dbContext.MdrBooleanTypes; } }
        public DbSet<MdrCharteringType> MdrCharteringTypes { get { return dbContext.MdrCharteringTypes; } }
        public DbSet<MdrCommEquipType> MdrCommEquipTypes { get { return dbContext.MdrCommEquipTypes; } }
        public DbSet<MdrConversionFactor> MdrConversionFactors { get { return dbContext.MdrConversionFactors; } }
        public DbSet<MdrCountryCurrency> MdrCountryCurrencies { get { return dbContext.MdrCountryCurrencies; } }
        public DbSet<MdrCrFishingCategory> MdrCrFishingCategories { get { return dbContext.MdrCrFishingCategories; } }
        public DbSet<MdrCrLandIndicator> MdrCrLandIndicators { get { return dbContext.MdrCrLandIndicators; } }
        public DbSet<MdrCrReportType> MdrCrReportTypes { get { return dbContext.MdrCrReportTypes; } }
        public DbSet<MdrCrSovWater> MdrCrSovWaters { get { return dbContext.MdrCrSovWaters; } }
        public DbSet<MdrCrUnit> MdrCrUnits { get { return dbContext.MdrCrUnits; } }
        public DbSet<MdrDataType> MdrDataTypes { get { return dbContext.MdrDataTypes; } }
        public DbSet<MdrDeckMachineryType> MdrDeckMachineryTypes { get { return dbContext.MdrDeckMachineryTypes; } }
        public DbSet<MdrEffortZone> MdrEffortZones { get { return dbContext.MdrEffortZones; } }
        public DbSet<MdrFaBaitType> MdrFaBaitTypes { get { return dbContext.MdrFaBaitTypes; } }
        public DbSet<MdrFaBftSizeCategory> MdrFaBftSizeCategories { get { return dbContext.MdrFaBftSizeCategories; } }
        public DbSet<MdrFaBrDef> MdrFaBrDefs { get { return dbContext.MdrFaBrDefs; } }
        public DbSet<MdrFaBrEu> MdrFaBrEus { get { return dbContext.MdrFaBrEus; } }
        public DbSet<MdrFaCatchType> MdrFaCatchTypes { get { return dbContext.MdrFaCatchTypes; } }
        public DbSet<MdrFaCharacteristic> MdrFaCharacteristics { get { return dbContext.MdrFaCharacteristics; } }
        public DbSet<MdrFaDeviceGearAttachment> MdrFaDeviceGearAttachments { get { return dbContext.MdrFaDeviceGearAttachments; } }
        public DbSet<MdrFaFishery> MdrFaFisheries { get { return dbContext.MdrFaFisheries; } }
        public DbSet<MdrFaGearCharacteristic> MdrFaGearCharacteristics { get { return dbContext.MdrFaGearCharacteristics; } }
        public DbSet<MdrFaGearProblem> MdrFaGearProblems { get { return dbContext.MdrFaGearProblems; } }
        public DbSet<MdrFaGearRecovery> MdrFaGearRecoveries { get { return dbContext.MdrFaGearRecoveries; } }
        public DbSet<MdrFaGearRole> MdrFaGearRoles { get { return dbContext.MdrFaGearRoles; } }
        public DbSet<MdrFaNeafcStock> MdrFaNeafcStocks { get { return dbContext.MdrFaNeafcStocks; } }
        public DbSet<MdrFaQueryParameter> MdrFaQueryParameters { get { return dbContext.MdrFaQueryParameters; } }
        public DbSet<MdrFaQueryType> MdrFaQueryTypes { get { return dbContext.MdrFaQueryTypes; } }
        public DbSet<MdrFaReasonArrival> MdrFaReasonArrivals { get { return dbContext.MdrFaReasonArrivals; } }
        public DbSet<MdrFaReasonDeparture> MdrFaReasonDepartures { get { return dbContext.MdrFaReasonDepartures; } }
        public DbSet<MdrFaReasonDiscard> MdrFaReasonDiscards { get { return dbContext.MdrFaReasonDiscards; } }
        public DbSet<MdrFaReasonEntry> MdrFaReasonEntries { get { return dbContext.MdrFaReasonEntries; } }
        public DbSet<MdrFaTripIdType> MdrFaTripIdTypes { get { return dbContext.MdrFaTripIdTypes; } }
        public DbSet<MdrFaVesselRole> MdrFaVesselRoles { get { return dbContext.MdrFaVesselRoles; } }
        public DbSet<MdrFaoFishingArea> MdrFaoFishingAreas { get { return dbContext.MdrFaoFishingAreas; } }
        public DbSet<MdrFaoSpecy> MdrFaoSpecies { get { return dbContext.MdrFaoSpecies; } }
        public DbSet<MdrFarFishCategory> MdrFarFishCategories { get { return dbContext.MdrFarFishCategories; } }
        public DbSet<MdrFarm> MdrFarms { get { return dbContext.MdrFarms; } }
        public DbSet<MdrFishFinderEquipType> MdrFishFinderEquipTypes { get { return dbContext.MdrFishFinderEquipTypes; } }
        public DbSet<MdrFishFreshness> MdrFishFreshnesses { get { return dbContext.MdrFishFreshnesses; } }
        public DbSet<MdrFishPackaging> MdrFishPackagings { get { return dbContext.MdrFishPackagings; } }
        public DbSet<MdrFishPresentation> MdrFishPresentations { get { return dbContext.MdrFishPresentations; } }
        public DbSet<MdrFishPreservation> MdrFishPreservations { get { return dbContext.MdrFishPreservations; } }
        public DbSet<MdrFishSizeCategory> MdrFishSizeCategories { get { return dbContext.MdrFishSizeCategories; } }
        public DbSet<MdrFishSizeClass> MdrFishSizeClasses { get { return dbContext.MdrFishSizeClasses; } }
        public DbSet<MdrFishingTripType> MdrFishingTripTypes { get { return dbContext.MdrFishingTripTypes; } }
        public DbSet<MdrFlapCharacteristic> MdrFlapCharacteristics { get { return dbContext.MdrFlapCharacteristics; } }
        public DbSet<MdrFlapCoastalParty> MdrFlapCoastalParties { get { return dbContext.MdrFlapCoastalParties; } }
        public DbSet<MdrFlapDocType> MdrFlapDocTypes { get { return dbContext.MdrFlapDocTypes; } }
        public DbSet<MdrFlapFlagState> MdrFlapFlagStates { get { return dbContext.MdrFlapFlagStates; } }
        public DbSet<MdrFlapIdType> MdrFlapIdTypes { get { return dbContext.MdrFlapIdTypes; } }
        public DbSet<MdrFlapQuotaType> MdrFlapQuotaTypes { get { return dbContext.MdrFlapQuotaTypes; } }
        public DbSet<MdrFlapRequestPurpose> MdrFlapRequestPurposes { get { return dbContext.MdrFlapRequestPurposes; } }
        public DbSet<MdrFlapWfStep> MdrFlapWfSteps { get { return dbContext.MdrFlapWfSteps; } }
        public DbSet<MdrFluxContactRole> MdrFluxContactRoles { get { return dbContext.MdrFluxContactRoles; } }
        public DbSet<MdrFluxFaFmc> MdrFluxFaFmcs { get { return dbContext.MdrFluxFaFmcs; } }
        public DbSet<MdrFluxFaReportType> MdrFluxFaReportTypes { get { return dbContext.MdrFluxFaReportTypes; } }
        public DbSet<MdrFluxFaType> MdrFluxFaTypes { get { return dbContext.MdrFluxFaTypes; } }
        public DbSet<MdrFluxGpMessageId> MdrFluxGpMessageIds { get { return dbContext.MdrFluxGpMessageIds; } }
        public DbSet<MdrFluxGpParty> MdrFluxGpParties { get { return dbContext.MdrFluxGpParties; } }
        public DbSet<MdrFluxGpPurpose> MdrFluxGpPurposes { get { return dbContext.MdrFluxGpPurposes; } }
        public DbSet<MdrFluxGpResponse> MdrFluxGpResponses { get { return dbContext.MdrFluxGpResponses; } }
        public DbSet<MdrFluxGpValLevel> MdrFluxGpValLevels { get { return dbContext.MdrFluxGpValLevels; } }
        public DbSet<MdrFluxGpValType> MdrFluxGpValTypes { get { return dbContext.MdrFluxGpValTypes; } }
        public DbSet<MdrFluxLocationChar> MdrFluxLocationChars { get { return dbContext.MdrFluxLocationChars; } }
        public DbSet<MdrFluxLocationType> MdrFluxLocationTypes { get { return dbContext.MdrFluxLocationTypes; } }
        public DbSet<MdrFluxMdrQueryType> MdrFluxMdrQueryTypes { get { return dbContext.MdrFluxMdrQueryTypes; } }
        public DbSet<MdrFluxProcessType> MdrFluxProcessTypes { get { return dbContext.MdrFluxProcessTypes; } }
        public DbSet<MdrFluxSalesPartyIdType> MdrFluxSalesPartyIdTypes { get { return dbContext.MdrFluxSalesPartyIdTypes; } }
        public DbSet<MdrFluxSalesPartyRole> MdrFluxSalesPartyRoles { get { return dbContext.MdrFluxSalesPartyRoles; } }
        public DbSet<MdrFluxSalesQueryParam> MdrFluxSalesQueryParams { get { return dbContext.MdrFluxSalesQueryParams; } }
        public DbSet<MdrFluxSalesQueryParamRole> MdrFluxSalesQueryParamRoles { get { return dbContext.MdrFluxSalesQueryParamRoles; } }
        public DbSet<MdrFluxSalesType> MdrFluxSalesTypes { get { return dbContext.MdrFluxSalesTypes; } }
        public DbSet<MdrFluxTelecomUse> MdrFluxTelecomUses { get { return dbContext.MdrFluxTelecomUses; } }
        public DbSet<MdrFluxUnit> MdrFluxUnits { get { return dbContext.MdrFluxUnits; } }
        public DbSet<MdrFluxVehicleIdType> MdrFluxVehicleIdTypes { get { return dbContext.MdrFluxVehicleIdTypes; } }
        public DbSet<MdrFluxVesselAdminType> MdrFluxVesselAdminTypes { get { return dbContext.MdrFluxVesselAdminTypes; } }
        public DbSet<MdrFluxVesselConstrType> MdrFluxVesselConstrTypes { get { return dbContext.MdrFluxVesselConstrTypes; } }
        public DbSet<MdrFluxVesselDimType> MdrFluxVesselDimTypes { get { return dbContext.MdrFluxVesselDimTypes; } }
        public DbSet<MdrFluxVesselEngineRole> MdrFluxVesselEngineRoles { get { return dbContext.MdrFluxVesselEngineRoles; } }
        public DbSet<MdrFluxVesselEquipType> MdrFluxVesselEquipTypes { get { return dbContext.MdrFluxVesselEquipTypes; } }
        public DbSet<MdrFluxVesselGearRole> MdrFluxVesselGearRoles { get { return dbContext.MdrFluxVesselGearRoles; } }
        public DbSet<MdrFluxVesselHistChar> MdrFluxVesselHistChars { get { return dbContext.MdrFluxVesselHistChars; } }
        public DbSet<MdrFluxVesselIdType> MdrFluxVesselIdTypes { get { return dbContext.MdrFluxVesselIdTypes; } }
        public DbSet<MdrFluxVesselPositionType> MdrFluxVesselPositionTypes { get { return dbContext.MdrFluxVesselPositionTypes; } }
        public DbSet<MdrFluxVesselQueryParam> MdrFluxVesselQueryParams { get { return dbContext.MdrFluxVesselQueryParams; } }
        public DbSet<MdrFluxVesselQueryType> MdrFluxVesselQueryTypes { get { return dbContext.MdrFluxVesselQueryTypes; } }
        public DbSet<MdrFluxVesselRegstrType> MdrFluxVesselRegstrTypes { get { return dbContext.MdrFluxVesselRegstrTypes; } }
        public DbSet<MdrFluxVesselReportType> MdrFluxVesselReportTypes { get { return dbContext.MdrFluxVesselReportTypes; } }
        public DbSet<MdrFluxVesselTechType> MdrFluxVesselTechTypes { get { return dbContext.MdrFluxVesselTechTypes; } }
        public DbSet<MdrGearType> MdrGearTypes { get { return dbContext.MdrGearTypes; } }
        public DbSet<MdrGender> MdrGenders { get { return dbContext.MdrGenders; } }
        public DbSet<MdrGfcmGsa> MdrGfcmGsas { get { return dbContext.MdrGfcmGsas; } }
        public DbSet<MdrLocation> MdrLocations { get { return dbContext.MdrLocations; } }
        public DbSet<MdrManagementArea> MdrManagementAreas { get { return dbContext.MdrManagementAreas; } }
        public DbSet<MdrMdmBr> MdrMdmBrs { get { return dbContext.MdrMdmBrs; } }
        public DbSet<MdrMdmBrDef> MdrMdmBrDefs { get { return dbContext.MdrMdmBrDefs; } }
        public DbSet<MdrMemberState> MdrMemberStates { get { return dbContext.MdrMemberStates; } }
        public DbSet<MdrNavigEquipType> MdrNavigEquipTypes { get { return dbContext.MdrNavigEquipTypes; } }
        public DbSet<MdrProductDestination> MdrProductDestinations { get { return dbContext.MdrProductDestinations; } }
        public DbSet<MdrPropellerType> MdrPropellerTypes { get { return dbContext.MdrPropellerTypes; } }
        public DbSet<MdrQuotaLocation> MdrQuotaLocations { get { return dbContext.MdrQuotaLocations; } }
        public DbSet<MdrQuotaObject> MdrQuotaObjects { get { return dbContext.MdrQuotaObjects; } }
        public DbSet<MdrRfmo> MdrRfmos { get { return dbContext.MdrRfmos; } }
        public DbSet<MdrSalesBr> MdrSalesBrs { get { return dbContext.MdrSalesBrs; } }
        public DbSet<MdrSalesBrDef> MdrSalesBrDefs { get { return dbContext.MdrSalesBrDefs; } }
        public DbSet<MdrStatRect> MdrStatRects { get { return dbContext.MdrStatRects; } }
        public DbSet<MdrStorageType> MdrStorageTypes { get { return dbContext.MdrStorageTypes; } }
        public DbSet<MdrTargetSpeciesGroup> MdrTargetSpeciesGroups { get { return dbContext.MdrTargetSpeciesGroups; } }
        public DbSet<MdrTerritory> MdrTerritories { get { return dbContext.MdrTerritories; } }
        public DbSet<MdrUnDataType> MdrUnDataTypes { get { return dbContext.MdrUnDataTypes; } }
        public DbSet<MdrVehicleType> MdrVehicleTypes { get { return dbContext.MdrVehicleTypes; } }
        public DbSet<MdrVesselActivity> MdrVesselActivities { get { return dbContext.MdrVesselActivities; } }
        public DbSet<MdrVesselBr> MdrVesselBrs { get { return dbContext.MdrVesselBrs; } }
        public DbSet<MdrVesselBrDef> MdrVesselBrDefs { get { return dbContext.MdrVesselBrDefs; } }
        public DbSet<MdrVesselCategory> MdrVesselCategories { get { return dbContext.MdrVesselCategories; } }
        public DbSet<MdrVesselCrewType> MdrVesselCrewTypes { get { return dbContext.MdrVesselCrewTypes; } }
        public DbSet<MdrVesselEvent> MdrVesselEvents { get { return dbContext.MdrVesselEvents; } }
        public DbSet<MdrVesselExportType> MdrVesselExportTypes { get { return dbContext.MdrVesselExportTypes; } }
        public DbSet<MdrVesselHullType> MdrVesselHullTypes { get { return dbContext.MdrVesselHullTypes; } }
        public DbSet<MdrVesselPhotoType> MdrVesselPhotoTypes { get { return dbContext.MdrVesselPhotoTypes; } }
        public DbSet<MdrVesselPort> MdrVesselPorts { get { return dbContext.MdrVesselPorts; } }
        public DbSet<MdrVesselPublicAidType> MdrVesselPublicAidTypes { get { return dbContext.MdrVesselPublicAidTypes; } }
        public DbSet<MdrVesselSegment> MdrVesselSegments { get { return dbContext.MdrVesselSegments; } }
        public DbSet<MdrVesselStorageType> MdrVesselStorageTypes { get { return dbContext.MdrVesselStorageTypes; } }
        public DbSet<MdrVesselType> MdrVesselTypes { get { return dbContext.MdrVesselTypes; } }
        public DbSet<MdrVmsBr> MdrVmsBrs { get { return dbContext.MdrVmsBrs; } }
        public DbSet<MdrVmsBrDef> MdrVmsBrDefs { get { return dbContext.MdrVmsBrDefs; } }
        public DbSet<MdrVmsBrParam> MdrVmsBrParams { get { return dbContext.MdrVmsBrParams; } }
        public DbSet<MdrVmsSatelliteOper> MdrVmsSatelliteOpers { get { return dbContext.MdrVmsSatelliteOpers; } }
        public DbSet<MdrWeightMeasureType> MdrWeightMeasureTypes { get { return dbContext.MdrWeightMeasureTypes; } }
        public DbSet<NaddressType> NaddressTypes { get { return dbContext.NaddressTypes; } }
        public DbSet<NapplicationStatus> NapplicationStatuses { get { return dbContext.NapplicationStatuses; } }
        public DbSet<NapplicationStatusHierarchy> NapplicationStatusHierarchies { get { return dbContext.NapplicationStatusHierarchies; } }
        public DbSet<NapplicationStatusHierarchyType> NapplicationStatusHierarchyTypes { get { return dbContext.NapplicationStatusHierarchyTypes; } }
        public DbSet<NapplicationType> NapplicationTypes { get { return dbContext.NapplicationTypes; } }
        public DbSet<NapplicationTypeGroup> NapplicationTypeGroups { get { return dbContext.NapplicationTypeGroups; } }
        public DbSet<NapplicationTypeHierType> NapplicationTypeHierTypes { get { return dbContext.NapplicationTypeHierTypes; } }
        public DbSet<NapplicationTypeTariff> NapplicationTypeTariffs { get { return dbContext.NapplicationTypeTariffs; } }
        public DbSet<NaquacultureInstallationType> NaquacultureInstallationTypes { get { return dbContext.NaquacultureInstallationTypes; } }
        public DbSet<NaquaculturePowerSupplyType> NaquaculturePowerSupplyTypes { get { return dbContext.NaquaculturePowerSupplyTypes; } }
        public DbSet<NaquacultureWaterAreaType> NaquacultureWaterAreaTypes { get { return dbContext.NaquacultureWaterAreaTypes; } }
        public DbSet<NaquacultureStatus> NaquacultureStatuses { get { return dbContext.NaquacultureStatuses; } }
        public DbSet<NauditLogActionType> NauditLogActionTypes { get { return dbContext.NauditLogActionTypes; } }
        public DbSet<NauditLogTable> NauditLogTables { get { return dbContext.NauditLogTables; } }
        public DbSet<NbuyerLicenseType> NbuyerLicenseTypes { get { return dbContext.NbuyerLicenseTypes; } }
        public DbSet<NbuyerType> NbuyerTypes { get { return dbContext.NbuyerTypes; } }
        public DbSet<NcancellationReason> NcancellationReasons { get { return dbContext.NcancellationReasons; } }
        public DbSet<NcatchFishUnloadType> NcatchFishUnloadTypes { get { return dbContext.NcatchFishUnloadTypes; } }
        public DbSet<NcatchInspectionType> NcatchInspectionTypes { get { return dbContext.NcatchInspectionTypes; } }
        public DbSet<NcatchZone> NcatchZones { get { return dbContext.NcatchZones; } }
        public DbSet<NchangeOfCircumstancesType> NchangeOfCircumstancesTypes { get { return dbContext.NchangeOfCircumstancesTypes; } }
        public DbSet<NcheckResolution> NcheckResolutions { get { return dbContext.NcheckResolutions; } }
        public DbSet<NcommercialFishingPermitLicenseType> NcommercialFishingPermitLicenseTypes { get { return dbContext.NcommercialFishingPermitLicenseTypes; } }
        public DbSet<NcommercialFishingPermitType> NcommercialFishingPermitTypes { get { return dbContext.NcommercialFishingPermitTypes; } }
        public DbSet<NconfiscationAction> NconfiscationActions { get { return dbContext.NconfiscationActions; } }
        public DbSet<NconfiscationInstitution> NconfiscationInstitutions { get { return dbContext.NconfiscationInstitutions; } }
        public DbSet<Ncountry> Ncountries { get { return dbContext.Ncountries; } }
        public DbSet<Ncourt> Ncourts { get { return dbContext.Ncourts; } }
        public DbSet<NdeliveryType> NdeliveryTypes { get { return dbContext.NdeliveryTypes; } }
        public DbSet<Ndepartment> Ndepartments { get { return dbContext.Ndepartments; } }
        public DbSet<Ndistrict> Ndistricts { get { return dbContext.Ndistricts; } }
        public DbSet<NdocumentType> NdocumentTypes { get { return dbContext.NdocumentTypes; } }
        public DbSet<NemployeeStatType> NemployeeStatTypes { get { return dbContext.NemployeeStatTypes; } }
        public DbSet<NemployeeStatTypeGroup> NemployeeStatTypeGroups { get { return dbContext.NemployeeStatTypeGroups; } }
        public DbSet<NeventType> NeventTypes { get { return dbContext.NeventTypes; } }
        public DbSet<NeventTypeGroup> NeventTypeGroups { get { return dbContext.NeventTypeGroups; } }
        public DbSet<News> News { get { return dbContext.News; } }
        public DbSet<NewsDistrict> NewsDistricts { get { return dbContext.NewsDistricts; } }
        public DbSet<NewsDistrictUserSubscription> NewsDistrictUserSubscriptions { get { return dbContext.NewsDistrictUserSubscriptions; } }
        public DbSet<NewsFile> NewsFiles { get { return dbContext.NewsFiles; } }
        public DbSet<NfileType> NfileTypes { get { return dbContext.NfileTypes; } }
        public DbSet<Nfish> Nfishes { get { return dbContext.Nfishes; } }
        public DbSet<NfishFamily> NfishFamilies { get { return dbContext.NfishFamilies; } }
        public DbSet<NfishFreshness> NfishFreshnesses { get { return dbContext.NfishFreshnesses; } }
        public DbSet<NfishGroup> NfishGroups { get { return dbContext.NfishGroups; } }
        public DbSet<NfishPresentation> NfishPresentations { get { return dbContext.NfishPresentations; } }
        public DbSet<NfishSalePurpose> NfishSalePurposes { get { return dbContext.NfishSalePurposes; } }
        public DbSet<NfishSizeCategory> NfishSizeCategories { get { return dbContext.NfishSizeCategories; } }
        public DbSet<NfishingGear> NfishingGears { get { return dbContext.NfishingGears; } }
        public DbSet<NfishingGearMarkStatus> NfishingGearMarkStatuses { get { return dbContext.NfishingGearMarkStatuses; } }
        public DbSet<NfishingGearPingerStatus> NfishingGearPingerStatuses { get { return dbContext.NfishingGearPingerStatuses; } }
        public DbSet<NfishingGearType> NfishingGearTypes { get { return dbContext.NfishingGearTypes; } }
        public DbSet<NfishingGearCheckReason> NfishingGearCheckReasons { get { return dbContext.NfishingGearCheckReasons; } }
        public DbSet<NfishingGearRecheckReason> NfishingGearRecheckReasons { get { return dbContext.NfishingGearRecheckReasons; } }

        public DbSet<NfishSex> NfishSexes { get { return dbContext.NfishSexes; } }
        public DbSet<NfleetType> NfleetTypes { get { return dbContext.NfleetTypes; } }
        public DbSet<NfuelType> NfuelTypes { get { return dbContext.NfuelTypes; } }
        public DbSet<Ngender> Ngenders { get { return dbContext.Ngenders; } }
        public DbSet<NgrossTonageStatInterval> NgrossTonageStatIntervals { get { return dbContext.NgrossTonageStatIntervals; } }
        public DbSet<NhatcheryEquipmentType> NhatcheryEquipmentTypes { get { return dbContext.NhatcheryEquipmentTypes; } }
        public DbSet<NholderGroundsForUseType> NholderGroundsForUseTypes { get { return dbContext.NholderGroundsForUseTypes; } }
        public DbSet<NhullMaterial> NhullMaterials { get { return dbContext.NhullMaterials; } }
        public DbSet<NinspDeliveryConfirmationType> NinspDeliveryConfirmationTypes { get { return dbContext.NinspDeliveryConfirmationTypes; } }
        public DbSet<NinspDeliveryType> NinspDeliveryTypes { get { return dbContext.NinspDeliveryTypes; } }
        public DbSet<NinspectedPersonType> NinspectedPersonTypes { get { return dbContext.NinspectedPersonTypes; } }
        public DbSet<NinspectionCheckType> NinspectionCheckTypes { get { return dbContext.NinspectionCheckTypes; } }
        public DbSet<NinspectionObservationTextCategory> NinspectionObservationTextCategories { get { return dbContext.NinspectionObservationTextCategories; } }
        public DbSet<NinspectionState> NinspectionStates { get { return dbContext.NinspectionStates; } }
        public DbSet<NinspectionType> NinspectionTypes { get { return dbContext.NinspectionTypes; } }
        public DbSet<NinstallationBasinMaterialType> NinstallationBasinMaterialTypes { get { return dbContext.NinstallationBasinMaterialTypes; } }
        public DbSet<NinstallationBasinPurposeType> NinstallationBasinPurposeTypes { get { return dbContext.NinstallationBasinPurposeTypes; } }
        public DbSet<NinstallationCollectorType> NinstallationCollectorTypes { get { return dbContext.NinstallationCollectorTypes; } }
        public DbSet<NinstallationNetCageType> NinstallationNetCageTypes { get { return dbContext.NinstallationNetCageTypes; } }
        public DbSet<Ninstitution> Ninstitutions { get { return dbContext.Ninstitutions; } }
        public DbSet<NlogBookType> NlogBookTypes { get { return dbContext.NlogBookTypes; } }
        public DbSet<NlogBookStatus> NlogBookStatuses { get { return dbContext.NlogBookStatuses; } }
        public DbSet<NmobileVersion> NmobileVersions { get { return dbContext.NmobileVersions; } }
        public DbSet<Nmunicipality> Nmunicipalities { get { return dbContext.Nmunicipalities; } }
        public DbSet<NnomenclatureGroup> NnomenclatureGroups { get { return dbContext.NnomenclatureGroups; } }
        public DbSet<NnomenclatureTable> NnomenclatureTables { get { return dbContext.NnomenclatureTables; } }
        public DbSet<NnotificationTemplate> NnotificationTemplates { get { return dbContext.NnotificationTemplates; } }
        public DbSet<NnumericStatType> NnumericStatTypes { get { return dbContext.NnumericStatTypes; } }
        public DbSet<NnumericStatTypeGroup> NnumericStatTypeGroups { get { return dbContext.NnumericStatTypeGroups; } }
        public DbSet<NobservationTool> NobservationTools { get { return dbContext.NobservationTools; } }
        public DbSet<NpageCode> NpageCodes { get { return dbContext.NpageCodes; } }
        public DbSet<NpatrolVehicleType> NpatrolVehicleTypes { get { return dbContext.NpatrolVehicleTypes; } }
        public DbSet<NpaymentStatus> NPaymentStatuses { get { return dbContext.NpaymentStatuses; } }
        public DbSet<NpaymentType> NpaymentTypes { get { return dbContext.NpaymentTypes; } }
        public DbSet<NpenalAuthorityType> NpenalAuthorityTypes { get { return dbContext.NpenalAuthorityTypes; } }
        public DbSet<NpenalDecreeStatusType> NpenalDecreeStatusTypes { get { return dbContext.NpenalDecreeStatusTypes; } }
        public DbSet<Npermission> Npermissions { get { return dbContext.Npermissions; } }
        public DbSet<NpermissionGroup> NpermissionGroups { get { return dbContext.NpermissionGroups; } }
        public DbSet<NpermissionType> NpermissionTypes { get { return dbContext.NpermissionTypes; } }
        public DbSet<NpermitReason> NpermitReasons { get { return dbContext.NpermitReasons; } }
        public DbSet<NpermitStatus> NpermitStatuses { get { return dbContext.NpermitStatuses; } }
        public DbSet<NpopulatedArea> NpopulatedAreas { get { return dbContext.NpopulatedAreas; } }
        public DbSet<Nport> Nports { get { return dbContext.Nports; } }
        public DbSet<NportGroup> NportGroups { get { return dbContext.NportGroups; } }
        public DbSet<NpoundNetCategoryType> NpoundNetCategoryTypes { get { return dbContext.NpoundNetCategoryTypes; } }
        public DbSet<NpoundNetSeasonType> NpoundNetSeasonTypes { get { return dbContext.NpoundNetSeasonTypes; } }
        public DbSet<NpoundNetStatus> NpoundNetStatuses { get { return dbContext.NpoundNetStatuses; } }
        public DbSet<NpublicAidType> NpublicAidTypes { get { return dbContext.NpublicAidTypes; } }
        public DbSet<NreportParameter> NReportParameters { get { return dbContext.NreportParameters; } }
        public DbSet<NrequiredFileType> NrequiredFileTypes { get { return dbContext.NrequiredFileTypes; } }
        public DbSet<NreworkProductType> NreworkProductTypes { get { return dbContext.NreworkProductTypes; } }
        public DbSet<NsailArea> NsailAreas { get { return dbContext.NsailAreas; } }
        public DbSet<Nsector> Nsectors { get { return dbContext.Nsectors; } }
        public DbSet<Nsegment> Nsegments { get { return dbContext.Nsegments; } }
        public DbSet<NshipAssociation> NshipAssociations { get { return dbContext.NshipAssociations; } }
        public DbSet<NstatisticalFormType> NstatisticalFormTypes { get { return dbContext.NstatisticalFormTypes; } }
        public DbSet<NsubmittedByRole> NsubmittedByRoles { get { return dbContext.NsubmittedByRoles; } }
        public DbSet<NsuspensionReason> NsuspensionReasons { get { return dbContext.NsuspensionReasons; } }
        public DbSet<NsuspensionType> NsuspensionTypes { get { return dbContext.NsuspensionTypes; } }
        public DbSet<NsystemParameter> NsystemParameters { get { return dbContext.NsystemParameters; } }
        public DbSet<Ntariff> Ntariffs { get { return dbContext.Ntariffs; } }
        public DbSet<NterritoryUnit> NterritoryUnits { get { return dbContext.NterritoryUnits; } }
        public DbSet<NticketPeriod> NticketPeriods { get { return dbContext.NticketPeriods; } }
        public DbSet<NticketStatus> NticketStatuses { get { return dbContext.NticketStatuses; } }
        public DbSet<NticketType> NticketTypes { get { return dbContext.NticketTypes; } }
        public DbSet<NtranslationGroup> NtranslationGroups { get { return dbContext.NtranslationGroups; } }
        public DbSet<NtranslationResource> NtranslationResources { get { return dbContext.NtranslationResources; } }
        public DbSet<NtransportVehicleType> NtransportVehicleTypes { get { return dbContext.NtransportVehicleTypes; } }
        public DbSet<NturbotSizeGroup> NturbotSizeGroups { get { return dbContext.NturbotSizeGroups; } }
        public DbSet<NusageDocumentType> NusageDocumentTypes { get { return dbContext.NusageDocumentTypes; } }
        public DbSet<NvesselActivity> NvesselActivities { get { return dbContext.NvesselActivities; } }
        public DbSet<NvesselLengthStatInterval> NvesselLengthStatIntervals { get { return dbContext.NvesselLengthStatIntervals; } }
        public DbSet<NvesselType> NvesselTypes { get { return dbContext.NvesselTypes; } }
        public DbSet<NviolationSignalType> NviolationSignalTypes { get { return dbContext.NviolationSignalTypes; } }
        public DbSet<NwaterBodyType> NwaterBodyTypes { get { return dbContext.NwaterBodyTypes; } }
        public DbSet<NwaterLawCertificateType> NwaterLawCertificateTypes { get { return dbContext.NwaterLawCertificateTypes; } }
        public DbSet<NwaterType> NwaterTypes { get { return dbContext.NwaterTypes; } }
        public DbSet<ObservationAtSea> ObservationsAtSea { get { return dbContext.ObservationAtSeas; } }
        public DbSet<OriginDeclaration> OriginDeclarations { get { return dbContext.OriginDeclarations; } }
        public DbSet<OriginDeclarationFish> OriginDeclarationFish { get { return dbContext.OriginDeclarationFishes; } }
        public DbSet<PenalDecreePaymentSchedule> PenalDecreePaymentSchedules { get { return dbContext.PenalDecreePaymentSchedules; } }
        public DbSet<PenalDecreeSeizedFishingGear> PenalDecreeSeizedFishingGears { get { return dbContext.PenalDecreeSeizedFishingGears; } }
        public DbSet<PenalDecreeStatus> PenalDecreeStatuses { get { return dbContext.PenalDecreeStatuses; } }
        public DbSet<PenalDecreesRegister> PenalDecreesRegisters { get { return dbContext.PenalDecreesRegisters; } }
        public DbSet<PenalDecreesRegisterFile> PenalDecreesRegisterFiles { get { return dbContext.PenalDecreesRegisterFiles; } }
        public DbSet<PermitLicenseRegisterFish> PermitLicenseRegisterFish { get { return dbContext.PermitLicenseRegisterFishes; } }
        public DbSet<PermitLicenseRegisterFishingGear> PermitLicenseRegisterFishingGears { get { return dbContext.PermitLicenseRegisterFishingGears; } }
        public DbSet<PermitLicenseSuspensionChangeHistory> CommercialFishingPermitLicenseSuspensionChangeHistories { get { return dbContext.PermitLicenseSuspensionChangeHistories; } }
        public DbSet<FvmsfishingActivityReport> FvmsfishingActivityReports { get { return dbContext.FvmsfishingActivityReports; } }
        public DbSet<FvmsfishingActivityReportLogBookPage> FvmsfishingActivityReportLogBookPages { get { return dbContext.FvmsfishingActivityReportLogBookPages; } }
        public DbSet<PermitLicensesRegister> CommercialFishingPermitLicensesRegisters { get { return dbContext.PermitLicensesRegisters; } }
        public DbSet<PermitLicensesRegisterFile> CommercialFishingPermitLicensesRegisterFile { get { return dbContext.PermitLicensesRegisterFiles; } }
        public DbSet<PermitRegister> CommercialFishingPermitRegisters { get { return dbContext.PermitRegisters; } }
        public DbSet<PermitRegisterFile> CommercialFishingPermitRegisterFiles { get { return dbContext.PermitRegisterFiles; } }
        public DbSet<PermitRegisterFish> PermitRegisterFish { get { return dbContext.PermitRegisterFishes; } }
        public DbSet<PermitSuspensionChangeHistory> CommercialFishingPermitSuspensionChangeHistories { get { return dbContext.PermitSuspensionChangeHistories; } }
        public DbSet<MapWaterTypePermitType> MapWaterTypePermitTypes { get { return dbContext.MapWaterTypePermitTypes; } }
        public DbSet<Person> Persons { get { return dbContext.Persons; } }
        public DbSet<PersonAddress> PersonAddresses { get { return dbContext.PersonAddresses; } }
        public DbSet<PersonDocument> PersonDocuments { get { return dbContext.PersonDocuments; } }
        public DbSet<PersonEmailAddress> PersonEmailAddresses { get { return dbContext.PersonEmailAddresses; } }
        public DbSet<PersonFile> PersonFiles { get { return dbContext.PersonFiles; } }
        public DbSet<PersonPhoneNumber> PersonPhoneNumbers { get { return dbContext.PersonPhoneNumbers; } }
        public DbSet<PhoneNumber> PhoneNumbers { get { return dbContext.PhoneNumbers; } }
        public DbSet<PoundNetCoordinate> PoundNetCoordinates { get { return dbContext.PoundNetCoordinates; } }
        public DbSet<PoundNetRegister> PoundNetRegisters { get { return dbContext.PoundNetRegisters; } }
        public DbSet<Report> Reports { get { return dbContext.Reports; } }
        public DbSet<ReportGroup> ReportGroups { get { return dbContext.ReportGroups; } }
        public DbSet<ReportParameter> ReportParameters { get { return dbContext.ReportParameters; } }
        public DbSet<ReportRolePermission> ReportRolePermissions { get { return dbContext.ReportRolePermissions; } }
        public DbSet<ReportUserPermission> ReportUserPermissions { get { return dbContext.ReportUserPermissions; } }
        public DbSet<ReworkForm> ReworkForms { get { return dbContext.ReworkForms; } }
        public DbSet<ReworkProduct> ReworkProducts { get { return dbContext.ReworkProducts; } }
        public DbSet<ReworkRawMaterial> ReworkRawMaterials { get { return dbContext.ReworkRawMaterials; } }
        public DbSet<Role> Roles { get { return dbContext.Roles; } }
        public DbSet<RolePermission> RolePermissions { get { return dbContext.RolePermissions; } }
        public DbSet<ScientificPermitOuting> ScientificPermitOutings { get { return dbContext.ScientificPermitOutings; } }
        public DbSet<ScientificPermitOutingCatch> ScientificPermitOutingCatches { get { return dbContext.ScientificPermitOutingCatches; } }
        public DbSet<ScientificPermitOwner> ScientificPermitOwners { get { return dbContext.ScientificPermitOwners; } }
        public DbSet<ScientificPermitReason> ScientificPermitReasons { get { return dbContext.ScientificPermitReasons; } }
        public DbSet<ScientificPermitRegister> ScientificPermitRegisters { get { return dbContext.ScientificPermitRegisters; } }
        public DbSet<ScientificPermitRegisterFile> ScientificPermitRegisterFiles { get { return dbContext.ScientificPermitRegisterFiles; } }
        public DbSet<ShipCapacityRegister> ShipCapacityRegister { get { return dbContext.ShipCapacityRegisters; } }
        public DbSet<ShipCatchQuota> ShipCatchQuotas { get { return dbContext.ShipCatchQuotas; } }
        public DbSet<ShipCatchQuotasHist> ShipCatchQuotasHists { get { return dbContext.ShipCatchQuotasHists; } }
        public DbSet<ShipInspection> ShipInspections { get { return dbContext.ShipInspections; } }
        public DbSet<ShipLogBookPage> ShipLogBookPages { get { return dbContext.ShipLogBookPages; } }
        public DbSet<ShipLogBookPageFile> ShipLogBookPageFiles { get { return dbContext.ShipLogBookPageFiles; } }
        public DbSet<ShipOwner> ShipOwners { get { return dbContext.ShipOwners; } }
        public DbSet<ShipRegister> ShipsRegister { get { return dbContext.ShipRegisters; } }
        public DbSet<ShipRegisterFile> ShipRegisterFiles { get { return dbContext.ShipRegisterFiles; } }
        public DbSet<StatisticalFormsRegisterFile> StatisticalFormsRegisterFiles { get { return dbContext.StatisticalFormsRegisterFiles; } }
        public DbSet<StatisticalFormsRegister> StatisticalFormsRegister { get { return dbContext.StatisticalFormsRegisters; } }
        public DbSet<TransportVehicleInspection> TransportVehicleInspections { get { return dbContext.TransportVehicleInspections; } }
        public DbSet<TransportationLogBookPage> TransportationLogBookPages { get { return dbContext.TransportationLogBookPages; } }
        public DbSet<TransportationLogBookPageFile> TransportationLogBookPageFiles { get { return dbContext.TransportationLogBookPageFiles; } }
        public DbSet<UnregisteredPerson> UnregisteredPersons { get { return dbContext.UnregisteredPersons; } }
        public DbSet<UnregisteredVessel> UnregisteredVessels { get { return dbContext.UnregisteredVessels; } }
        public DbSet<UsageDocument> UsageDocuments { get { return dbContext.UsageDocuments; } }
        public DbSet<User> Users { get { return dbContext.Users; } }
        public DbSet<UserInfo> UserInfos { get { return dbContext.UserInfos; } }
        public DbSet<UserLegal> UserLegals { get { return dbContext.UserLegals; } }
        public DbSet<UserMobileDevice> UserMobileDevices { get { return dbContext.UserMobileDevices; } }
        public DbSet<UserRole> UserRoles { get { return dbContext.UserRoles; } }
        public DbSet<VesselDaysAtSea> VesselDaysAtSeas { get { return dbContext.VesselDaysAtSeas; } }
        public DbSet<WaterObjectCheck> WaterObjectChecks { get { return dbContext.WaterObjectChecks; } }
        public DbSet<WorkerQueue> WorkerQueues { get { return dbContext.WorkerQueues; } }
        public DbSet<AquacultureFormFullSystemInstallation> AquacultureFormFullSystemInstallations { get { return dbContext.AquacultureFormFullSystemInstallations; } }
        public DbSet<AquacultureFormNonFullSystemInstallation> AquacultureFormNonFullSystemInstallations { get { return dbContext.AquacultureFormNonFullSystemInstallations; } }
        public DbSet<NotificationsLog> NotificationsLogs { get { return dbContext.NotificationsLogs; } }
        public DbSet<Nauanstatus> Nauanstatuses { get { return dbContext.Nauanstatuses; } }
        public DbSet<NpenalDecreeType> NpenalDecreeTypes { get { return dbContext.NpenalDecreeTypes; } }
        public DbSet<NpenalDecreeSanctionType> NpenalDecreeSanctionTypes { get { return dbContext.NpenalDecreeSanctionTypes; } }
        public DbSet<PenalDecreeSanction> PenalDecreeSanctions { get { return dbContext.PenalDecreeSanctions; } }
        public DbSet<PenalPointComplaintStatus> PenalPointComplaintStatuses { get { return dbContext.PenalPointComplaintStatuses; } }
        public DbSet<PenalPointsRegister> PenalPointsRegister { get { return dbContext.PenalPointsRegisters; } }
        public DbSet<NpenalPointStatus> NpenalPointStatuses { get { return dbContext.NpenalPointStatuses; } }
        public DbSet<Auanwitness> Auanwitnesses { get { return dbContext.Auanwitnesses; } }
        public DbSet<NconfiscatedAppliance> NconfiscatedAppliances { get { return dbContext.NconfiscatedAppliances; } }
        public DbSet<PenalDecreeFishCompensation> PenalDecreeFishCompensations { get { return dbContext.PenalDecreeFishCompensations; } }
        public DbSet<DuplicatesRegister> DuplicatesRegister { get { return dbContext.DuplicatesRegisters; } }
        public DbSet<DuplicatesRegisterFile> DuplicatesRegisterFiles { get { return dbContext.DuplicatesRegisterFiles; } }
    }
}
