// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Пределен риболовен капацитет
    /// </summary>
    [Table("CountryCapacityRegister", Schema = "RCap")]
    public partial class CountryCapacityRegister
    {
        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Дата на регламента
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime RegulationDate { get; set; }
        /// <summary>
        /// Регламент на ЕС
        /// </summary>
        [Required]
        [StringLength(500)]
        public string Regulation { get; set; }
        /// <summary>
        /// Бруто тонаж
        /// </summary>
        public decimal GrossTonnage { get; set; }
        /// <summary>
        /// Мощност (kW)
        /// </summary>
        public decimal EnginePower { get; set; }
        /// <summary>
        /// Начална дата на валидност на записа
        /// </summary>
        public DateTime ValidFrom { get; set; }
        /// <summary>
        /// Крайна дата на валидност на записа
        /// </summary>
        public DateTime ValidTo { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }
    }
}