// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Групи риболовни уреди
    /// </summary>
    [Table("NFishingGearTypes", Schema = "Noms")]
    [Index(nameof(MdrGearTypeId), Name = "IXFK_NFishingGearTypes_MDR_Gear_Type")]
    [Index(nameof(ValidTo), nameof(Code), Name = "UK_ISS_NFishingGearTypes", IsUnique = true)]
    public partial class NfishingGearType
    {
        public NfishingGearType()
        {
            NfishingGears = new HashSet<NfishingGear>();
        }

        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Трибуквен код
        /// </summary>
        [Required]
        [StringLength(3)]
        public string Code { get; set; }
        /// <summary>
        /// Име
        /// </summary>
        [Required]
        [StringLength(500)]
        public string Name { get; set; }
        /// <summary>
        /// Идентификатор във FLUX
        /// </summary>
        [Column("MDR_Gear_Type_ID")]
        public int? MdrGearTypeId { get; set; }
        /// <summary>
        /// Флаг - дали типът уред има куки (за да се посочва броят им при стр. от риболовен дневник)
        /// </summary>
        public bool HasHooks { get; set; }
        /// <summary>
        /// Начална дата на валидност на записа
        /// </summary>
        public DateTime ValidFrom { get; set; }
        /// <summary>
        /// Крайна дата на валидност на записа
        /// </summary>
        public DateTime ValidTo { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(MdrGearTypeId))]
        [InverseProperty("NfishingGearTypes")]
        public virtual MdrGearType MdrGearType { get; set; }
        [InverseProperty(nameof(NfishingGear.GearType))]
        public virtual ICollection<NfishingGear> NfishingGears { get; set; }
    }
}