// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Общини
    /// </summary>
    [Table("NMunicipalities", Schema = "Noms")]
    [Index(nameof(DistrictId), Name = "IXFK_NMunicipalities_NRegions")]
    [Index(nameof(Code), nameof(ValidTo), Name = "UK_Noms_NMunicipalities", IsUnique = true)]
    public partial class Nmunicipality
    {
        public Nmunicipality()
        {
            Addresses = new HashSet<Address>();
            NpopulatedAreas = new HashSet<NpopulatedArea>();
            PoundNetRegisters = new HashSet<PoundNetRegister>();
        }

        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// код
        /// </summary>
        [Required]
        [StringLength(10)]
        public string Code { get; set; }
        /// <summary>
        /// Име
        /// </summary>
        [Required]
        [StringLength(500)]
        public string Name { get; set; }
        /// <summary>
        /// Област
        /// </summary>
        [Column("DistrictID")]
        public int DistrictId { get; set; }
        /// <summary>
        /// Начална дата на валидност на записа
        /// </summary>
        public DateTime ValidFrom { get; set; }
        /// <summary>
        /// Крайна дата на валидност на записа
        /// </summary>
        public DateTime ValidTo { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(DistrictId))]
        [InverseProperty(nameof(Ndistrict.Nmunicipalities))]
        public virtual Ndistrict District { get; set; }
        [InverseProperty(nameof(Address.Municipality))]
        public virtual ICollection<Address> Addresses { get; set; }
        [InverseProperty(nameof(NpopulatedArea.Municipality))]
        public virtual ICollection<NpopulatedArea> NpopulatedAreas { get; set; }
        [InverseProperty(nameof(PoundNetRegister.Municipality))]
        public virtual ICollection<PoundNetRegister> PoundNetRegisters { get; set; }
    }
}