// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    [Table("MDR_VMS_BR", Schema = "FLUX_Vessel_Position")]
    public partial class MdrVmsBr
    {
        [Key]
        [Column("ID")]
        public override int Id { get; set; }
        [StringLength(50)]
        public override string Code { get; set; }
        [StringLength(500)]
        public string EnDescription { get; set; }
        public DateTime ValidFrom { get; set; }
        public DateTime ValidTo { get; set; }
        [StringLength(500)]
        public string CreatedBy { get; set; }
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        [Column("BRReference")]
        [StringLength(14)]
        public string Brreference { get; set; }
        [Column("BRRes")]
        [StringLength(3)]
        public string Brres { get; set; }
        [StringLength(1)]
        public string ActiveInd { get; set; }
    }
}