// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    [Table("MDR_Location", Schema = "FLUX_General")]
    public partial class MdrLocation
    {
        public MdrLocation()
        {
            Nports = new HashSet<Nport>();
        }

        [Key]
        [Column("ID")]
        public override int Id { get; set; }
        [Required]
        [StringLength(50)]
        public override string Code { get; set; }
        [StringLength(500)]
        public string EnDescription { get; set; }
        public DateTime ValidFrom { get; set; }
        public DateTime ValidTo { get; set; }
        [StringLength(500)]
        public string CreatedBy { get; set; }
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        [Column("iso3")]
        [StringLength(3)]
        public string Iso3 { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        public float? Latitude { get; set; }
        public float? Longitude { get; set; }
        [StringLength(5)]
        public string FishingPort { get; set; }
        [StringLength(5)]
        public string LandingPlace { get; set; }
        [StringLength(5)]
        public string CommercialPort { get; set; }
        [Column("UNLoCode")]
        [StringLength(5)]
        public string UnloCode { get; set; }
        [StringLength(12)]
        public string Coordinates { get; set; }
        [StringLength(8)]
        public string Function { get; set; }

        [InverseProperty(nameof(Nport.MdrLocation))]
        public virtual ICollection<Nport> Nports { get; set; }
    }
}