// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    [Table("MDR_Territory", Schema = "FLUX_General")]
    public partial class MdrTerritory
    {
        public MdrTerritory()
        {
            Ncountries = new HashSet<Ncountry>();
        }

        [Key]
        [Column("ID")]
        public override int Id { get; set; }
        [Required]
        [StringLength(50)]
        public override string Code { get; set; }
        [StringLength(500)]
        public string EnDescription { get; set; }
        public DateTime ValidFrom { get; set; }
        public DateTime ValidTo { get; set; }
        [StringLength(500)]
        public string CreatedBy { get; set; }
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        [Column("startdate")]
        [StringLength(10)]
        public string Startdate { get; set; }
        [Column("enddate")]
        [StringLength(10)]
        public string Enddate { get; set; }
        [StringLength(3158)]
        public string EnName { get; set; }
        [StringLength(1)]
        public string LandLockInd { get; set; }

        [InverseProperty(nameof(Ncountry.MdrTerritory))]
        public virtual ICollection<Ncountry> Ncountries { get; set; }
    }
}