// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    [Table("MDR_Vessel_Type", Schema = "FLUX_General")]
    public partial class MdrVesselType
    {
        public MdrVesselType()
        {
            NvesselTypes = new HashSet<NvesselType>();
        }

        [Key]
        [Column("ID")]
        public override int Id { get; set; }
        [Required]
        [StringLength(50)]
        public override string Code { get; set; }
        [Required]
        [StringLength(500)]
        public string EnDescription { get; set; }
        public DateTime ValidFrom { get; set; }
        public DateTime ValidTo { get; set; }
        [StringLength(500)]
        public string CreatedBy { get; set; }
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        [Column("ISSCFVCode")]
        [StringLength(6)]
        public string Isscfvcode { get; set; }
        [StringLength(30)]
        public string VesselCat { get; set; }
        [StringLength(2)]
        public string ParentVessel { get; set; }

        [InverseProperty(nameof(NvesselType.MdrVesselType))]
        public virtual ICollection<NvesselType> NvesselTypes { get; set; }
    }
}