// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Страници от дневник за приемане (декларации за Приемане)
    /// </summary>
    [Table("AdmissionLogBookPages", Schema = "CatchSales")]
    [Index(nameof(CreatedBy), nameof(UpdatedBy), Name = "IDX_CatchSales_AdmissionLogBookPages_Migration")]
    [Index(nameof(LogBookPermitLicenseId), Name = "IXFK_AdmissionLogBookPages_LogBookPermitLicenses")]
    [Index(nameof(LogBookId), Name = "IXFK_AdmissionLogBookPages_LogBooks")]
    [Index(nameof(OriginDeclarationId), Name = "IXFK_AdmissionLogBookPages_OriginDeclarations")]
    [Index(nameof(TransportationDocumentId), Name = "IXFK_AdmissionLogBookPages_TransportationLogBookPages")]
    [Index(nameof(PageNum), Name = "UK_CatchSales_AdmissionLogBookPages_Num", IsUnique = true)]
    public partial class AdmissionLogBookPage
    {
        public AdmissionLogBookPage()
        {
            AdmissionLogBookPageFiles = new HashSet<AdmissionLogBookPageFile>();
            FirstSaleLogBookPages = new HashSet<FirstSaleLogBookPage>();
            InspectionLogBookPages = new HashSet<InspectionLogBookPage>();
            LogBookPageProducts = new HashSet<LogBookPageProduct>();
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("LogBookID")]
        public int LogBookId { get; set; }
        /// <summary>
        /// Удостоверение към дневник
        /// </summary>
        [Column("LogBookPermitLicenseID")]
        public int? LogBookPermitLicenseId { get; set; }
        /// <summary>
        /// Номер на страница
        /// </summary>
        public decimal PageNum { get; set; }
        /// <summary>
        /// Уникален идентификатор във FLUX
        /// </summary>
        public Guid FluxIdentifier { get; set; }
        /// <summary>
        /// Статус на страницата (InProgress, Submitted, Canceled, Missing)
        /// </summary>
        [Required]
        [StringLength(50)]
        public string Status { get; set; }
        /// <summary>
        /// Декларация за произход
        /// </summary>
        [Column("OriginDeclarationID")]
        public int? OriginDeclarationId { get; set; }
        /// <summary>
        /// Документ за превоз
        /// </summary>
        [Column("TransportationDocumentID")]
        public int? TransportationDocumentId { get; set; }
        /// <summary>
        /// Дата на предаване
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime? HandoverDate { get; set; }
        /// <summary>
        /// Място на складиране
        /// </summary>
        [StringLength(500)]
        public string StorageLocation { get; set; }
        /// <summary>
        /// Причина за анулиране (при статус Canceled)
        /// </summary>
        [StringLength(4000)]
        public string CancelationReason { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(LogBookId))]
        [InverseProperty("AdmissionLogBookPages")]
        public virtual LogBook LogBook { get; set; }
        [ForeignKey(nameof(LogBookPermitLicenseId))]
        [InverseProperty("AdmissionLogBookPages")]
        public virtual LogBookPermitLicense LogBookPermitLicense { get; set; }
        [ForeignKey(nameof(OriginDeclarationId))]
        [InverseProperty("AdmissionLogBookPages")]
        public virtual OriginDeclaration OriginDeclaration { get; set; }
        [ForeignKey(nameof(TransportationDocumentId))]
        [InverseProperty(nameof(TransportationLogBookPage.AdmissionLogBookPages))]
        public virtual TransportationLogBookPage TransportationDocument { get; set; }
        [InverseProperty(nameof(AdmissionLogBookPageFile.Record))]
        public virtual ICollection<AdmissionLogBookPageFile> AdmissionLogBookPageFiles { get; set; }
        [InverseProperty(nameof(FirstSaleLogBookPage.AdmissionLogBookPage))]
        public virtual ICollection<FirstSaleLogBookPage> FirstSaleLogBookPages { get; set; }
        [InverseProperty(nameof(InspectionLogBookPage.AdmissionLogBookPage))]
        public virtual ICollection<InspectionLogBookPage> InspectionLogBookPages { get; set; }
        [InverseProperty(nameof(LogBookPageProduct.AdmissionLogBookPage))]
        public virtual ICollection<LogBookPageProduct> LogBookPageProducts { get; set; }
    }
}
