// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Размерна група на улов от първа продажба
    /// </summary>
    [Table("NFishSizeCategories", Schema = "CatchSales")]
    [Index(nameof(MdrFishSizeCategoryId), Name = "IXFK_NFishSizeCategories_MDR_Fish_Size_Category")]
    [Index(nameof(Code), nameof(ValidTo), Name = "UK_CatchSales_NFishSizeCategories", IsUnique = true)]
    public partial class NfishSizeCategory
    {
        public NfishSizeCategory()
        {
            LogBookPageProducts = new HashSet<LogBookPageProduct>();
        }

        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Код
        /// </summary>
        [Required]
        [StringLength(3)]
        public string Code { get; set; }
        /// <summary>
        /// Име
        /// </summary>
        [Required]
        [StringLength(500)]
        public string Name { get; set; }
        [Column("MDR_Fish_Size_Category_ID")]
        public int? MdrFishSizeCategoryId { get; set; }
        /// <summary>
        /// Начална дата на валидност на записа
        /// </summary>
        public DateTime ValidFrom { get; set; }
        /// <summary>
        /// Крайна дата на валидност на записа
        /// </summary>
        public DateTime ValidTo { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(MdrFishSizeCategoryId))]
        [InverseProperty("NfishSizeCategories")]
        public virtual MdrFishSizeCategory MdrFishSizeCategory { get; set; }
        [InverseProperty(nameof(LogBookPageProduct.FishSizeCategory))]
        public virtual ICollection<LogBookPageProduct> LogBookPageProducts { get; set; }
    }
}