// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Детайлен лог на промените по обектите в базата
    /// </summary>
    [Table("AuditLog", Schema = "SysLog")]
    public partial class AuditLog
    {
        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Дата на действие
        /// </summary>
        public DateTime LogDate { get; set; }
        /// <summary>
        /// Потребител
        /// </summary>
        [Required]
        [StringLength(500)]
        public string Username { get; set; }
        /// <summary>
        /// IP адрес на потребителя
        /// </summary>
        [Required]
        [Column("IPAddress")]
        [StringLength(46)]
        public string Ipaddress { get; set; }
        /// <summary>
        /// Информация за браузера на потребителя
        /// </summary>
        [Required]
        [StringLength(500)]
        public string BrowserInfo { get; set; }
        /// <summary>
        /// Приложение в системата (Area)
        /// </summary>
        [Required]
        [StringLength(500)]
        public string Application { get; set; }
        /// <summary>
        /// Действие (контролер/метод)
        /// </summary>
        [Required]
        [StringLength(500)]
        public string Action { get; set; }
        /// <summary>
        /// Тип действие (Insert/Update/Delete)
        /// </summary>
        [Required]
        [StringLength(50)]
        public string ActionType { get; set; }
        /// <summary>
        /// Име на схема в базата
        /// </summary>
        [Required]
        [StringLength(256)]
        public string SchemaName { get; set; }
        /// <summary>
        /// Таблица, в която е направена промяната
        /// </summary>
        [Required]
        [StringLength(256)]
        public string TableName { get; set; }
        /// <summary>
        /// Първичен ключ на записа, който е променен
        /// </summary>
        [Column("TableID")]
        [StringLength(40)]
        public string TableId { get; set; }
        /// <summary>
        /// Стара стойност
        /// </summary>
        public string OldValue { get; set; }
        /// <summary>
        /// Нова стойност
        /// </summary>
        public string NewValue { get; set; }
    }
}