// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Телефонни номера на юридически лица
    /// </summary>
    [Table("LegalPhoneNumbers", Schema = "Legals")]
    [Index(nameof(LegalId), Name = "IXFK_ISS_LegalPhoneNumbers_ISS_Legals")]
    [Index(nameof(PhoneId), Name = "IXFK_ISS_LegalPhoneNumbers_ISS_PhoneNumbers")]
    [Index(nameof(PhoneId), nameof(LegalId), Name = "UK_ISS_LegalPhoneNumbers", IsUnique = true)]
    public partial class LegalPhoneNumber
    {         public LegalPhoneNumber()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Юридическо лице
        /// </summary>
        [Column("LegalID")]
        public int LegalId { get; set; }
        /// <summary>
        /// Телефон
        /// </summary>
        [Column("PhoneID")]
        public int PhoneId { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(LegalId))]
        [InverseProperty("LegalPhoneNumbers")]
        public virtual Legal Legal { get; set; }
        [ForeignKey(nameof(PhoneId))]
        [InverseProperty(nameof(PhoneNumber.LegalPhoneNumbers))]
        public virtual PhoneNumber Phone { get; set; }
    }
}
