namespace IARA.FluxInspectionModels
{
    [Serializable]
    [XmlType(Namespace = "urn:un:unece:uncefact:codelist:standard:UNECE:AdjustmentReasonDescriptionCode_Financial:D22A")]
    [XmlRoot("AdjustmentReasonDescriptionCodeFinancial", Namespace = "urn:un:unece:uncefact:codelist:standard:UNECE:AdjustmentReasonDescriptionCode_Financial:D22A", IsNullable = false)]
    public enum AdjustmentReasonDescriptionCodeFinancialContentType
    {

        [XmlEnum("1")]
        Item1,
        [XmlEnum("5")]
        Item5,
        [XmlEnum("7")]
        Item7,
        [XmlEnum("8")]
        Item8,
        [XmlEnum("9")]
        Item9,
        [XmlEnum("10")]
        Item10,
        [XmlEnum("11")]
        Item11,
        [XmlEnum("12")]
        Item12,
        [XmlEnum("13")]
        Item13,
        [XmlEnum("19")]
        Item19,
        [XmlEnum("20")]
        Item20,
        [XmlEnum("21")]
        Item21,
        [XmlEnum("22")]
        Item22,
        [XmlEnum("23")]
        Item23,
        [XmlEnum("24")]
        Item24,
        [XmlEnum("25")]
        Item25,
        [XmlEnum("26")]
        Item26,
        [XmlEnum("27")]
        Item27,
        [XmlEnum("30")]
        Item30,
        [XmlEnum("34")]
        Item34,
        [XmlEnum("36")]
        Item36,
        [XmlEnum("37")]
        Item37,
        [XmlEnum("38")]
        Item38,
        [XmlEnum("39")]
        Item39,
        [XmlEnum("40")]
        Item40,
        [XmlEnum("41")]
        Item41,
        [XmlEnum("42")]
        Item42,
        [XmlEnum("43")]
        Item43,
        [XmlEnum("44")]
        Item44,
        [XmlEnum("45")]
        Item45,
        [XmlEnum("46")]
        Item46,
        [XmlEnum("47")]
        Item47,
        [XmlEnum("48")]
        Item48,
        [XmlEnum("50")]
        Item50,
        [XmlEnum("52")]
        Item52,
        [XmlEnum("53")]
        Item53,
        [XmlEnum("54")]
        Item54,
        [XmlEnum("55")]
        Item55,
        [XmlEnum("56")]
        Item56,
        [XmlEnum("57")]
        Item57,
        [XmlEnum("58")]
        Item58,
        [XmlEnum("59")]
        Item59,
        [XmlEnum("60")]
        Item60,
        [XmlEnum("61")]
        Item61,
        [XmlEnum("62")]
        Item62,
        [XmlEnum("63")]
        Item63,
        [XmlEnum("64")]
        Item64,
        [XmlEnum("65")]
        Item65,
        [XmlEnum("66")]
        Item66,
        [XmlEnum("67")]
        Item67,
        [XmlEnum("68")]
        Item68,
        [XmlEnum("69")]
        Item69,
        [XmlEnum("70")]
        Item70,
        [XmlEnum("73")]
        Item73,
        [XmlEnum("74")]
        Item74,
        [XmlEnum("75")]
        Item75,
        [XmlEnum("77")]
        Item77,
        [XmlEnum("78")]
        Item78,
        [XmlEnum("79")]
        Item79,
        [XmlEnum("80")]
        Item80,
        [XmlEnum("81")]
        Item81,
        [XmlEnum("82")]
        Item82,
        [XmlEnum("83")]
        Item83,
        [XmlEnum("84")]
        Item84,
        [XmlEnum("85")]
        Item85,
        [XmlEnum("86")]
        Item86,
        [XmlEnum("87")]
        Item87,
        [XmlEnum("88")]
        Item88,
        [XmlEnum("89")]
        Item89,
        [XmlEnum("90")]
        Item90,
        [XmlEnum("91")]
        Item91,
        [XmlEnum("92")]
        Item92,
        [XmlEnum("93")]
        Item93,
        [XmlEnum("94")]
        Item94,
        [XmlEnum("95")]
        Item95,
        [XmlEnum("96")]
        Item96,
        [XmlEnum("97")]
        Item97,
        [XmlEnum("98")]
        Item98,
        [XmlEnum("99")]
        Item99,
        [XmlEnum("100")]
        Item100,
        ZZZ,
    }
}