namespace IARA.FluxInspectionModels
{
    [Serializable]
    [XmlType(Namespace = "urn:un:unece:uncefact:codelist:standard:UNECE:CommunicationMeansTypeCode:D22A")]
    [XmlRoot("CommunicationMeansTypeCode", Namespace = "urn:un:unece:uncefact:codelist:standard:UNECE:CommunicationMeansTypeCode:D22A", IsNullable = false)]
    public enum CommunicationMeansTypeCodeContentType
    {

        AA,
        AB,
        AC,
        AD,
        AE,
        AF,
        AG,
        AH,
        AI,
        AJ,
        AK,
        AL,
        AM,
        AN,
        AO,
        AP,
        AQ,
        AR,
        AS,
        AT,
        AU,
        AV,
        AW,
        CA,
        EI,
        EM,
        EX,
        FT,
        FX,
        GM,
        IE,
        IM,
        MA,
        PB,
        PS,
        SW,
        TE,
        TG,
        TL,
        TM,
        TT,
        TX,
        XF,
        XG,
        XH,
        XI,
        XJ,
    }
}