// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Основания за ползване на помещение от купувач
    /// </summary>
    [Table("BuyerPremiseUsageDocuments", Schema = "RCPP")]
    [Index(nameof(UsageDocumentId), Name = "IXFK_BuyerPremiseUsageDocuments_UsageDocuments")]
    [Index(nameof(BuyerId), Name = "IXFK_RCPP_BuyerUsageDocuments_RCPP_BuyersRegister")]
    [Index(nameof(BuyerId), nameof(UsageDocumentId), Name = "UK_RCPP_BuyerUsageDocuments", IsUnique = true)]
    public partial class BuyerPremiseUsageDocument
    {         public BuyerPremiseUsageDocument()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Регистриран купувач
        /// </summary>
        [Column("BuyerID")]
        public int BuyerId { get; set; }
        /// <summary>
        /// Документ за ползване
        /// </summary>
        [Column("UsageDocumentID")]
        public int UsageDocumentId { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(BuyerId))]
        [InverseProperty(nameof(BuyerRegister.BuyerPremiseUsageDocuments))]
        public virtual BuyerRegister Buyer { get; set; }
        [ForeignKey(nameof(UsageDocumentId))]
        [InverseProperty("BuyerPremiseUsageDocuments")]
        public virtual UsageDocument UsageDocument { get; set; }
    }
}
