// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IARA.EntityModels.Entities
{
    /// <summary>
    /// Прикачени файлове по регистър купувачи
    /// </summary>
    [Table("BuyerRegisterFiles", Schema = "RCPP")]
    [Index(nameof(FileTypeId), Name = "IXFK_BuyerRegisterFiles_NFileTypes")]
    [Index(nameof(FileId), Name = "IXFK_RCPP_BuyerRegisterFiles_ISS_Files")]
    [Index(nameof(RecordId), Name = "IXFK_RCPP_BuyerRegisterFiles_RCPP_BuyersRegister")]
    [Index(nameof(FileId), nameof(RecordId), nameof(FileTypeId), Name = "UK_RCPP_BuyerRegisterFiles", IsUnique = true)]
    public partial class BuyerRegisterFile
    {         public BuyerRegisterFile()
        {
            this.IsActive = true;
        }


        /// <summary>
        /// Уникален идентификатор
        /// </summary>
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        /// <summary>
        /// Тип на файла
        /// </summary>
        [Column("FileTypeID")]
        public int FileTypeId { get; set; }
        [Column("RecordID")]
        public int RecordId { get; set; }
        [Column("FileID")]
        public int FileId { get; set; }
        /// <summary>
        /// Флаг дали записът е активен или изтрит
        /// </summary>
        [Required]
        public bool IsActive { get; set; }
        /// <summary>
        /// Потребител създал записа
        /// </summary>
        [Required]
        [StringLength(500)]
        public string CreatedBy { get; set; }
        /// <summary>
        /// Дата и час на създаване на записа
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// Потребител последно актуализирал записа
        /// </summary>
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        /// <summary>
        /// Дата и час на последна актуализация на записа
        /// </summary>
        public DateTime? UpdatedOn { get; set; }

        [ForeignKey(nameof(FileId))]
        [InverseProperty("BuyerRegisterFiles")]
        public virtual File File { get; set; }
        [ForeignKey(nameof(FileTypeId))]
        [InverseProperty(nameof(NfileType.BuyerRegisterFiles))]
        public virtual NfileType FileType { get; set; }
        [ForeignKey(nameof(RecordId))]
        [InverseProperty(nameof(BuyerRegister.BuyerRegisterFiles))]
        public virtual BuyerRegister Record { get; set; }
    }
}
